AlgorithmWithJava/study

1주차/재모/Programmers_택배 배달과 수거하기.java

최소 이동 거리를 구하기 위해서는 가장 뒤에 있는 배달/수거부터 끝내야 함을 인지했고, 그리디로 풀어야겠다고 생각했습니다.
1. 각 시점마다 상자를 나타내는 변수를 정의하고, 각 집마다 deliveries[i], pickups[i] 만큼을 감소시킴
2. 상자가 0보다 작다면, 용량이 부족하다는 뜻이므로 cap을 더하고, 한번 더 왕복시키는 방식으로 반복함
- 시간 복잡도: 하나의 for문으로 각 집을 한 번씩만 순회하므로 `O(n)`
- 공간 복잡도: 추가적인 변수는 d, p, answer 뿐이므로 `O(1)`
이러한 그리디 문제는 설계가 꼬이면 구현 로직이 굉장히 복잡해지므로, 처음 설계가 중요한 것 같습니다.

[한재모 / 프로그래머스 Lv.2] 택배 배달과 수거하기

---

1주차/semin/Programers_택배 배달과 수거하기.java
2주차/semin/BOJ_회의실 배정.java

가장 먼 집을 목적지로 삼은 뒤 가는 길에는 배달만 하고, 다시 물류창고로 돌아갈 때는 수거만 하는 방식의 그리디 문제이다.
1. 스택에는 배달할/수거할 택배 상자의 위치를 배달할/수거할 택배 상자의 개수만큼 push한다.
2. 가장 멀리 떨어진 배달/수거해야 할 집을 구하고 해당 값을 answer에 더해준다. 그리고, cap개수만큼 pop한다.
- 시간복잡도: O(cap * n) = O(50  * 100,000)
→ 스택에 있는 원소가 모두 pop될 때까지 while문과 for문을 반복
- 공간복잡도: O(cap * n) = O(50  * 100,000)
→ 스택에 들어갈 수 있는 최대 원소 수 
그리디에 정당성을 부여하는 것에 시간을 오래 썼고, 스택을 활용하여 구현하는 과정 중에 0인 값을 처리하는 것에 번거로움을 느꼈다. 새로운 그리디 문제를 배워가고, 상자 개수만큼 위치정보를 스택에 집어넣는 방법을 배워갈 수 있었다.

[박세민 / 프로그래머스 Lv.2] 택배 배달과 수거하기

---

2주차/huiyeong/BOJ_카드 정렬하기.java
2주차/huiyeong/BOJ_회의실 배정.java

겹치지 않게 하면서 최대 개수라는 조건에서 그리디 알고리즘을 사용해야 한다고 생각하게 되었습니다.
그리디 알고리즘은 각 선택이 그 순간의 최적을 고르는 방식으로, 이 문제에서는 회의가 끝나는 시간이 빠른 순으로 정렬하여 가능한 한 많은 회의를 선택하는 방식으로 풀 수 있습니다.
- 시간 복잡도: O(N log N) 
- Arrays.sort()으로 인해 시간 복잡도는 O(N log N)입니다. 
- 공간 복잡도: O(1) 
그리디 알고리즘의 핵심은 매 선택이 최선이 되어야 한다는 점입니다.
이번 문제에서, 회의가 끝나는 시간이 빠른 순으로 정렬하고, 그 회의들이 겹치지 않도록 조건을 체크하며 진행하는 방식으로 문제를 풀 수 있었습니다.
이 과정에서 그리디 알고리즘을 활용하는 방식에 대해 좀 더 확실히 이해할 수 있었고, 다음번 문제를 풀 때에도 이런 접근 방식을 빠르게 적용할 수 있을 것 같습니다.

[김희영 / BOJ 골드5] 회의실 배정

---

2주차/BOJ_회의실 배정.java

가장 빨리 끝나는 회의를 선택해야 하는 그리디 문제이다. 특히, ‘**한 회의가 끝나는 것과 동시에 다음 회의가 시작될 수 있다. 회의의 시작시간과 끝나는 시간이 같을 수도 있다. 이 경우에는 시작하자마자 끝나는 것으로 생각하면 된다.**’라는 조건을 만족하기 위해 끝나는 시간이 같은 회의의 경우 시작하는 시간을 기준으로 2차적 정렬을 해줘야 한다.
- 시간복잡도: O(n log n)
→ 회의 시간 정렬
- 공간복잡도: O(n)
→ 회의 시간 목록
‘**한 회의가 끝나는 것과 동시에 다음 회의가 시작될 수 있다. 회의의 시작시간과 끝나는 시간이 같을 수도 있다. 이 경우에는 시작하자마자 끝나는 것으로 생각하면 된다.**’라는 조건을 주의해야 했다. 항상 조건 잘 읽기

[박세민 / BOJ 골드5] 회의실 배정

---

2주차/semin/BOJ_카드 정렬하기.java

그리디 알고리즘 중 허프만 코드 알고리즘을 활용하여 풀 수 있는 문제이다.
- 시간복잡도: O(N log N)
→ 자바 우선순위큐 프레임워크를 사용하여 카드 정렬
- 공간복잡도: O(N)
→ 카드 수만큼 공간 사용
허프만 코드 알고리즘을 알고 있다면 어렵지 않은 문제였다

[박세민/ BOJ 골드4] 카드 정렬하기

---

2주차/jihee/카드 정렬하기.java

가장 작은 카드 두 묶음을 계속 합쳐나가야 전체 비교 횟수를 최소화할 수 있다.
→ 우선순위 큐(PriorityQueue)를 사용해 매번 최소값 두 개를 꺼내 합치는 그리디 방식으로 해결
시간 복잡도: O(N log N)
공간 복잡도: O(N)
우선순위 큐를 알고있다면 쉽게 풀 수 있는 문제였다.

[김지희/ BOJ 골드4] 카드 정렬하기

---

2주차/huiyeong/BOJ_카드 정렬하기.java

가장 적은 비용으로 묶는 전략으로, 매 순간 가장 작은 두 값을 선택해 합치는 것이 전체 최소 비용을 만드는 최적의 방법을 구하는 문제이기 때문에 그리드알고리즘을 사용해야 한다는 것을 알게 되었습니다.
처음에는 배열을 생각했지만 업데이트 되어도 계속 제일 작은 두 개를 골라야 했기 때문에 우선순위 큐를 사용하였습니다.
시간 복잡도 : O(N log N)
우선순위 큐에 N개의 원소를 넣는 데 O(N log N) 이후 큐에서 두 개를 꺼내고 다시 넣는 작업을 N-1번 반복하며, 각 작업마다 log N이 걸립니다.
공간 복잡도: O(N)
우선순위 큐에 N개의 값을 저장합니다.
우선순위 큐를 사용하기로 하고 실행 결과 NullPointerException 이 발생했습니다. while문 조건을 명확히 수립하지 않아 발생하였습니다. 이를 통해 조건문에 대해서 좀 더 생각하게 된 계기가 되었습니다.

[김희영 / BOJ 골드4] 카드 정렬하기

---

2주차/huiyeong/BOJ_단어 수학.java

문제를 봤을 때, 그리드 알고리즘을 써야겠다고 생각했습니다. 그러나 어떠한 식으로 데이터를 저장할지에 대해 고민을 한 결과 hashmap을 써서 가중치를 저장해야겠다고 생각했습니다. 
- 시간 복잡도 : O(N * L + K log K)
이중반복문 + map 정렬 때문입니다.
- 공간 복잡도 : O(K)
해시맵과 정렬을 함께 사용하는 방식으로, 문제를 구조적으로 해결하는 훈련이 되었습니다. 자바에서 Map.Entry를 ArrayList로 바꿔 정렬하는 패턴도 자주 쓰일 수 있을 것 같아 유용하게 느껴졌습니다.

[김희영/ BOJ 골드4] 단어 수학

---

2주차/jaemo/BOJ_단어 수학.java

우선 단어들을 배열에 저장하고, 가장 긴 단어의 길이를 기준으로 모든 단어를 오른쪽 정렬 형태로 정리합니다. 그리고나서 각 자리를 기준으로 해당 위치에 있는 알파벳이 차지하는 가중치를 계산했습니다.
- 시간: `O(nL)` L은 단어의 최대 글자수
- 공간: `O(nL)` L은 단어의 최대 글자수
문제를 접하자마자 어떤 알고리즘을 떠올렸다기보다는, 일단 자연스럽게 가중치를 계산하는 방식으로 풀었습니다. 
풀고나서 생각해보니 그리디 알고리즘임을 인지했습니다.

[한재모 / BOJ 골드4] 단어 수학

---

2주차/huiyeong/Programmers_할인 행사.java

처음 문제를 읽었을 때 연속 10일이고 하루씩 밀린다고 했을 때 슬라이딩 윈도우를 써야겠다고 생각했습니다.
또한 과일에 대해 개수가 있는 문제여서 hashMap을 써야겠다고 생각했습니다.
n = discount.length, m = want.length
- 시간 복잡도 : O(n*m)
슬라이딩 윈도우로 인해서 O(n) 이고 각 윈도우마다 비교하는 연산(match)때문에 O(m) 따라서 O(n*m)입니다.
- 공간 복잡도 :  O(m)
hashmap을 사용했기 때문입니다.
처음 구현할 때는 쉽게 풀어갔지만 마지막에 테스트를 실행했을 때 하나가 계속 틀렸습니다.  첫날부터 10일까지 일치하는 경우를 확인하지 않아서 였습니다. 이로 인해 조건을 정말 잘 풀어나가야 겠다고 생각했습니다.

[김희영 / 프로그래머스 Lv.2] 할인 행사

---

2주차/jihee/PG_할인 행사.java

1. want와 number를 기반으로 구매 희망 목록 map 생성
2. discount 배열을 10일 단위로 슬라이딩 윈도우 방식으로 순회
3. 매 윈도우마다 구매 항목 dMap을 구성하고, 원래 map과 동일한지 비교
4. 동일하면 answer += 1
✔ 핵심은 슬라이딩 윈도우 + Map 비교!
* 시간복잡도: O(N * M)
* 공간복잡도: O(M)
처음에는 문제의 10일 연속 조건을 고려하지 않아서 테스트케이스를 통과하지 못했고, 문제를 다시 읽으면서 10일 단위로 끊어서 검사해야 한다는 조건을 놓쳤다는 걸 알게 되었다. 문제를 잘읽자!

[김지희/ 프로그래머스 Lv.2] 할인 행사

---

2주차/jaemo/PG_할인 행사.java

우선, 문제 그대로 완전 탐색으로 해결 가능한지 판단했습니다. 할인 기간 10일과 입력 조건을 모두 고려해도 성능상 문제가 없다고 생각했고, 끝내 완전탐색으로 풀었습니다.
- 시간: `O(d*10*w)` (d: discount 배열 크기, w: want 배열 크기)
- 공간: `O(n)`
문제 접근 자체는 직관적이고 구현하기 쉬웠습니다. 하지만 완전탐색으로 풀었더니 반복 계산이 좀 많아서 입력 조건이 조금만 더 커지면 시간 초과가 발생할 것 같습니다.
HashMap을 사용해 미리 값들을 저장해놨다면, 성능을 최적화할 수 있을 것 [같습니다.](url)

[한재모 / 프로그래머스 Lv.2] 할인 행사

---

2주차/huiyeong/Programmers_괄호 회전하기.java

괄호를 반으로 나눌 때 동일해야 하기 때문에 스택을 사용해야 한다고 생각했습니다. 문제는 괄호를 한칸씩 옮겨야 하는 걸 코드로 구현하기 위해서 큐를 사용할까 싶었지만 그러면 괄호가 옮은지 확인하기가 힘들어질 것 같아 문자를 자르는 메소드를 사용해야겠다고 생각했습니다.
- 시간복잡도 : O(n^2)
이중for문이기 때문입니다.
- 공간복잡도 : O(n)
스택을 사용하기 때문입니다.
문제를 많이 풀 수록 다양한 방식이 떠오를 수 있는 것 같아서 더욱 열심히 해야겠다고 느낀 문제였습니다.

[김희영 / 프로그래머스 Lv.2] 괄호 회전하기

---

2주차/semin/Programmers_괄호 회전하기.java

문자열을 두 번 이어붙여 회전된 모든 경우를 슬라이딩 윈도우로 탐색한다. 각 회전에 대해 스택을 이용해 괄호의 유효성을 검사한다. 올바른 괄호일 경우만 카운트를 증가시킨다.
- **시간복잡도:** O(N²)
→ N번 회전 × 회전당 길이 N 만큼 검사
- **공간복잡도:** O(N)
→ 스택 최대 길이는 문자열 길이만큼
스택을 이용한 괄호 유효성 검사는 익숙했지만, 회전마다 초기화가 중요했다. 다음에도 비슷한 문제를 만난다면 모든 회전을 고려해야 함을 놓치지 않도록 주의해야겠다.

[박세민 / 프로그래머스 Lv.2] 괄호 회전하기

---

2주차/jihee/PG_괄호 회전하기.java

문자열의 길이만큼 회전하면서 각 회전된 문자열이 괄호 쌍이 맞는지 Stack을 활용하여 체크한다.
괄호가 정상적으로 닫혀서 stack이 비어 있으면 유효한 괄호 문자열로 카운트
시간 복잡도: O(N^2)
문자열 길이 N만큼 회전하고 각 회전에 대해 길이 N 스캔 ⇒ N * N
공간 복잡도: O(N)
Stack은 최대 N개의 문자 저장
괄호 여닫는걸보고 바로 스택을 떠올려서 풀긴 했다. 풀이에 틀린점은 없었긴 하지만 문제를 꼼꼼하게 안읽고 풀이를 시작해서 다음엔 문제를 잘읽고 풀어야겠다..!

[김지희/ 프로그래머스 Lv.2] 괄호 회전하기

---

2주차/jaemo/PG_괄호 회전하기.java
3주차/jaemo/BOJ_아기 상어.java

왼쪽 회전은 큐에서 요소를 뽑아서 다시 넣는 방식으로 구현했고, 올바른 문자열을 확인하는 과정을 스택을 사용해 풀었습니다.
- 시간: `O(n^2)`
- 공간: `O(n)`
큐와 스택을 안다면 쉽게 풀 수 있는 문제인 것 같습니다.
---
최단 거리를 구해야 한다는 점에서 BFS를 채택했으며, 먹을 수 있는 물고기에는 우선순위가 존재하므로, `distance > row > col` 순으로 정렬하도록 우선순위 큐를 사용했습니다.
- 시간: 최악의 경우 `O(n^4)`
- 공간: `O(n^2)`
설계를 탄탄하게 하지 않고 성급히 구현했더니 실수가 잦고 결국 길을 잃는 문제가 발생했어요. 이렇게 조건이 많고 복잡한 문제는 초기 설계가 중요함을 다시 한 번 체감했습니다.

[한재모 / 프로그래머스 Lv.2] 괄호 회전하기, [한재모 / BOJ 골드3] 아기 상어

---

3주차/semin/BOJ_아기 상어.java
3주차/semin/BOJ_인구 이동.java

BFS를 이용한 최단 거리를 탐색 문제였다. 가장 가까운, 위쪽&왼쪽 우선순위에 따라 먹을 물고기를 결정한다. 또한, 먹은 수가 나이만큼이면 아기 상어의 크기를 증가시킨다.
- **시간복잡도:** O(N^2 × M)
→ 물고기 M마리마다 BFS 수행
- **공간복잡도:** O(N^2)
→ 그래프, 방문 배열, 큐 모두 N^2 크기
우선순위 조건이 많아 정렬과 비교 조건을 꼼꼼히 구현하는 게 중요했다. 최적의 물고기를 찾기 위해 후보군 리스트를 따로 저장둬야 해서 코드가 길어졌다. 실수하지 않게 조심했어야 했다!..

[박세민/ BOJ 골드3] 아기 상어

---

3주차/huiyeong/BOJ_아기 상어.java

N×N 크기의 공간을 다 지나가야 하기 때문에 DFS, BFS 를 생각하게 되었습니다. 우선순위에 대해서 많이 생각해야 하는 문제였습니다.
- 시간 복잡도 : O(N^2)
while, for 문이기 때문입니다.
- 공간 복잡도 : O(N^2)
간단한 BFS 구현이 아니라 우선 순위가 존재하기 때문에 많이 복잡하게 느껴졌습니다.

[김희영/ BOJ 골드3] 아기 상어

---

3주차/BOJ_아기 상어.java

최단거리를 구해야 하는 BFS 문제! 
PriorityQueue를 이용해 먹을 수 있는 물고기 중 가장 위쪽, 그다음은 가장 왼쪽에 있는 물고기를 우선 선택한다.
시간 복잡도 : 매번 BFS를 돌기 때문에 O(N^2)
공간 복잡도 : O(N^2)
상어 크기도 고려해야 되고 우선순위을 고려해서 풀어야 하는게 좀 복잡하게 느껴졌다.

[김지희/BOJ 골드3]아기 상어 

---

3주차/BOJ_인구 이동.java

매 칸을 돌면서 방문하지 않은 칸에서 BFS 탐색을 시작해, 조건을 만족하는 이웃 국가들을 모아 연합을 구성한다.
BFS로 구성한 연합의 전체 인구 수를 평균내어, 연합 내 모든 칸에 인구를 재배분한다.
시간 복잡도 : O(N^2)
공간 복잡도: O(N^2)
BFS에 대해 더 공부할 수 있었다!

[김지희/ BOJ 골드4] 인구 이동

---

3주차/semin/BOJ_내리막 길.java

DFS로 모든 경로를 탐색하면서, 중복되는 계산은 DP로 저장해 최적화했다.
높은 지점에서 낮은 지점으로만 이동 가능한 내리막길 특성을 이용했다.
기저 조건은 도착지에 도달했을 때 1을 반환하는 방식이다.
- **시간복잡도:** O(M × N)
→ 모든 칸을 한 번씩 방문하며, DP로 중복 탐색 방지
- **공간복잡도:** O(M × N)
→ 지도 배열과 메모이제이션용 DP 배열 사용
처음엔 DFS만 사용해 시간 초과가 발생했지만, DP로 중복 계산을 줄이며 해결했다.
기저 조건과 메모이제이션 초기값(-1 설정)의 중요성을 다시 느꼈다.
경로 수를 세는 문제는 visited 대신 DP 배열을 사용하는 것이 효율적이다.

[박세민 / BOJ 골드3] 내리막 길

---

3주차/huiyeong/Programmers_셔틀버스.java

우선순위 큐를 사용해 크루들의 도착 시간을 오름차순으로 처리합니다. 각 셔틀에 대해서 최대 m명의 크루가 탑승할 수 있으며, 셔틀이 도착할 때 대기열에 있는 크루들이 최대한 빠르게 탑승하도록 합니다. 마지막 셔틀에 탑승한 크루가 가장 늦게 탑승한 사람이 되며, 그 시간에서 1분을 뺀 시간이 콘이 탑승할 수 있는 가장 늦은 시간이 됩니다.
- 시간 복잡도: O(k log k) (k: 크루의 수)
- 공간 복잡도: O(k)
조건을 잘 파악해야 겠다고 느꼈습니다.

[김희영 / 프로그래머스 Lv.3] 셔틀버스

---

3주차/semin/Programmers_셔틀버스.java

탑승 가능한 시간을 분으로 변환 후 정렬하여 시뮬레이션 방식으로 풀었다.
버스 시간마다 태울 수 있는 인원을 체크하고, 콘이 마지막 버스를 탈 수 있는 최적 시간을 계산한다.
- 시간복잡도: O(N log N)
→ 입력 시간 정렬에 O(N log N), 나머지 순회는 O(N)
- 공간복잡도: O(N)
→ 시간 배열을 따로 저장하는 데 O(N)
문제 조건이 많지만 시뮬레이션 흐름을 따라가면 어렵지 않다.
탑승 조건을 정확히 처리하는 것이 핵심 포인트였다.

[박세민 / 프로그래머스 Lv.3] 셔틀버스

---

4주차/semin/BOJ_톱니바퀴.java

회전 명령을 받아 현재 톱니부터 양옆으로 영향을 전달하며 회전 여부를 판단하고 시뮬레이션을 진행했다.
회전은 시계/반시계 방향을 구분하여 배열을 직접 수정하였다.
- 시간복잡도: O(K × 4)
→ 회전 명령마다 4개의 톱니를 모두 검사하고 회전할 수 있다.
- 공간복잡도: O(1)
→ 톱니바퀴 개수가 고정(4개)로 주어져 추가 메모리 사용이 거의 없다.
시뮬레이션 문제는 회전 조건과 방향 처리가 헷갈리기 쉽지만, 차분히 구현하면 충분히 풀 수 있다.

[박세민 / BOJ 골드5] 톱니바퀴

---

4주차/jaemo/BOJ_톱니바퀴.java

처음에는 회전하는 로직을 구현할 때 deque 자료구조를 사용할까 하다가, 맞닿은 극을 찾을 때는 결국 특정 인덱스에 접근해야 하기 때문에 배열을 사용했습니다.
- 시간: `O(32K)`
- 공간: `O(1)`
회전 전파만 잘 신경 써서 구현하면 어렵지 않은 문제인 듯 합니다.

[한재모 / BOJ 골드 5] 톱니바퀴

---

4주차/huiyeong/BOJ_톱니바퀴.java

처음에는 갱신 해줘야 하기 때문에 배열말고 큐를 사용할까 했지만 반대 방향으로도 회전할 수 있어야 하기 때문에 배열을 사용했습니다.
- 시간 복잡도: O(K × 4 × 8) (K: 회전 수)
- 공간 복잡도: O(4 × 8)
문제 조건을 놓치지 않고 구현해야겠다는 걸 느꼈습니다.

[김희영 / BOJ 골드 5] 톱니바퀴

---

4주차/jihee/BOJ_톱니바퀴.java

오른쪽 톱니바퀴: 현재 톱니의 2번(index 2)과 오른쪽 톱니의 6번(index 6)을 비교한다.
왼쪽 톱니바퀴: 현재 톱니의 6번(index 6)과 왼쪽 톱니의 2번(index 2)을 비교한다.
맞닿은 날이 서로 다르면, 반대 방향으로 회전시킨다.
시간복잡도 : O(K)
공간복잡도 : O(1)
구현 조건 빼먹지 말고 풀기!

[김지희/ BOJ 골드 5] 톱니바퀴

---

4주차/semin/BOJ_감시.java

모든 CCTV의 방향 조합을 완전탐색(DFS)하여 최소 사각지대 개수를 구한다.
CCTV가 감시하는 경로를 **0이 아닌 고유 번호(depth+1)** 로 칠해 구분한다. (기존 -1 사용 문제: 다른 CCTV끼리 덮어쓰기 문제 발생 → 해결)
`paintShap`, `removeShap` 함수로 칠하고 되돌리기를 반복한다.
- 시간 복잡도: O(4^4 × N × M)
- CCTV마다 최대 4방향 고려
- 매번 N×M 전체 사무실 상태를 확인해야 함
- 공간 복잡도: O(N × M)
단순한 시뮬레이션 문제도 작은 디테일(예: 감시 표시 방식)에 따라 결과가 완전히 달라질 수 있다는 걸 다시 느꼈다.

[박세민 / BOJ 골드3] 감시

---

4주차/jihee/BOJ_감시.java
4주차/jihee/BOJ_미세먼지안녕.java

커밋을 같은 브랜치에 해버려서 한번에 올릴게요!
CCTV번호별로 회전시켜서 사각지대의 최소값 출력
CCTV가 90도로 회전하는 경우를 체크 했을 때 
1번의 경우 4가지/ 2번 2가지 / 3번 4가지 / 4번 4가지 / 5번 1가지의 경우가 나온다.
시간복잡도 : O(4 ^ K ×N×M)
공간복잡도 : O(N × M)
CCTV를 단순히 회전시키는 조합 문제라고 생각했지만, 각 CCTV마다 감시 방향이 다르고, 회전 시 가능한 경우의 수가 다르기 때문에 더 꼼꼼하게 체크하고 문제를 풀어야 했다.
T초 후의 미세먼지 총량을 계산하는 문제
* 미세먼지
미세먼지가 있는 칸에서 4방향으로 퍼짐.
퍼질 수 있는 방향의 개수에 따라 (현재 먼지량 / 5) 만큼 확산
* 공기청정기
두 개의 청정기 위치(위, 아래)를 기준으로 공기를 순환시킴.
위쪽 청정기는 반시계 방향, 아래쪽 청정기는 시계 방향으로 회전
시간복잡도 : O(T × R × C)
공간복잡도: O(R × C)
문제 풀면서 자꾸 놓친 부분이 생기는데 요구사항을 꼼꼼하게 확인하고 풀어야겠다.

[김지희 / BOJ 골드3] 감시 , [김지희 / BOJ 골드4] 미세먼지 안녕!

---

4주차/semin/BOJ_미세먼지 안녕.java

공기청정기 위치를 기준으로 매 시간마다 미세먼지를 확산시키고, 상하 방향의 공기 순환을 시뮬레이션했다.
확산은 4방향 탐색, 정화는 반시계/시계 방향으로 값을 한 칸씩 이동시키며 구현했다.
시간복잡도: O(T × R × C)
→ 매 시간마다 모든 칸을 순회하며 확산 및 정화 연산을 수행한다.
공간복잡도: O(R × C)
→ 맵 복사를 위한 배열을 한 번 더 사용하며, 입력 크기만큼의 공간이 필요하다.
시뮬레이션 구현 문제는 단계별 처리 순서를 명확히 정리하고, 조건 분기를 꼼꼼히 확인하는 것이 중요했다.
특히 공기청정기 작동 시 좌표 경계 조건과 방향 배열 처리가 까다로웠다.

[박세민 / BOJ 골드4] 미세먼지 안녕

---

4주차/jaemo/BOJ_미세먼지 안녕!.java

로직을 크게 미세먼지 확산과 공기청정기 작동 2가지로 나누어 설계했습니다. 
미세먼지 확산은 dRow, dCol 배열을 이용해 퍼지도록 했고, 공기청정기 작동은 배열 요소 이동 방식으로 구현했습니다.
그리고 확산과 정화는 newMap 배열을 사용해 상태 충돌을 방지했습니다.
- 시간: `O(T*R*C)`
- 공간: `O(R*C)`
설계는 어렵지 않게 했지만, newMap을 매 반복마다 새로 초기화하는 과정에서 기존 상태와 newMap을 섞어 쓰는 실수로 디버깅에 시간이 걸렸습니다.

[한재모 | BOJ 골드 4] 미세먼지 안녕! 

---

4주차/jaemo/PG_이모티콘 할인행사.java

모든 할인 조합을 완전탐색하는 방식으로 풀었습니다.
n: 사용자 수, m: 이모티콘 수
- 시간: `O(n*m)`
- 공간: `O(m)`
백트래킹(완전탐색)만 잘 활용할 줄 알면 어렵지 않은 문제였던 것 같습니다.

[한재모 / 프로그래머스 Lv.2] 이모티콘 할인행사

---

4주차/jihee/이모티콘할인행사.java

이모티콘 각각에 대해 할인율을  설정하는 모든 경우의 수를 완탐으로 계산하는 문제
구매 금액이 사용자 기준 이상이면 이모티콘 플러스 서비스에 가입
아니면 할인가 기준으로 구매 금액을 누적
* 시간복잡도 : O(4^N)
* 공간복잡도 : O(N)
완탐으로 차근차근 풀다보니까 어렵지 않게 풀 수있었다!

[김지희 / 프로그래머스 Lv.2] 이모티콘 할인 행사

---

4주차/semin/Programmers_이모티콘 할인 행사.java

이모티콘별 할인율의 모든 조합을 완전탐색으로 시도하고, 각 경우마다 사용자 조건을 만족하는지 계산했다.
구매 금액이 기준을 넘으면 구독자로, 아니면 총 매출로 합산하였다.
시간복잡도: O(4^N × M)
→ 이모티콘 개수가 N일 때 4^N 조합, 각 조합마다 M명의 유저 확인.
공간복잡도: O(N)
→ 각 조합별 할인율 저장을 위한 배열만 추가 사용.
완전탐색 문제는 브루트포스 구조를 명확히 설정하면 어렵지 않게 풀 수 있다.
조건 분기만 잘 정리하면 깔끔한 코드가 가능했다.

[박세민 / 프로그래머스 Lv.2] 이모티콘 할인 행사

---

4주차/huiyeong/BOJ_미세먼지 안녕!.java
4주차/huiyeong/Programmers_이모티콘 할인행사.java

모든 가능한 경우를 하나하나씩 계산하고 최적의 결과를 찾는 방식이다보니 완전탐색 문제라는 것을 알았습니다. 
- 시간복잡도 : O(4^n * m)
- 공간복잡도 : O(n)
조합하는 부분에서 조금 막혔지만 출력하면서 나아가다보니 해결할 수 있었습니다.
구현 문제이기 때문에 차근차근 문제를 해결하려고 노력하였습니다.
- 시간복잡도 : O(R*C*T)
- 공간복잡도 : O(R * C)
배열 arr, temp 를 쓰기 때문입니다.
공기청정기 위치 부분에서 조금 헷갈렸지만 문제를 차분히 읽고 다시 도전하니 해결할 수 있었습니다.

[김희영 / 프로그래머스 Lv.2] 이모티콘 할인행사 , [김희영 / BOJ 골드4] 미세먼지 안녕!

---

4주차/huiyeong/Programmers_메뉴 리뉴얼.java

저번 문제와 비슷하게 조합을 생각해야 하는 문제라고 느꼈습니다. 
문제를 풀 수도 어떤 알고리즘인지 알 수 있다고 느꼈습니다.

[김희영 / 프로그래머스 Lv.2] 메뉴 리뉴얼

---

4주차/jaemo/PG_메뉴 리뉴얼.java

각 코스 메뉴 개수에 대해 모든 조합을 백트래킹으로 구한 뒤 hashMap에 저장하고, 해당 map에서 최댓값을 구하는 방식으로 풀었습니다.
- 시간: `O(n * 2^m)`
- 공간: `O(n)`
백트래킹을 이용한 조합 코드를 다시 상기시키는 기회가 되었습니다. 그리고 사소한 예외 조건(메뉴 순서 오름찬수)도 주의해야 함을 체감했어요.

[한재모 / 프로그래머스 Lv.2] 메뉴 리뉴얼

---

5주차/semin/BOJ_다이어트.java

모든 식재료 조합을 백트래킹으로 탐색하며 영양 기준을 만족하는 최소 비용 조합을 찾았다.
각 조합에 대해 영양성분을 누적 계산하고 조건을 만족할 경우 최소값을 갱신하였다.
시간복잡도: O(2^N)
→ 각 식재료를 선택하거나 선택하지 않는 모든 경우 탐색.
공간복잡도: O(N)
→ 조합 문자열 저장 및 재귀 호출 스택 사용.
완전탐색 문제지만 조건 분기와 가지치기를 통해 효율적인 풀이가 가능했다.
백트래킹에서 조합 문자열 관리와 조건 만족 시점 판단이 중요했다.

[박세민 / BOJ 골드4] 다이어트

---

5주차/jaemo/BOJ_다이어트.java

모든 경우의 수를 탐색하되, 중복 선택하지 않도록 했습니다.
그리고 조합마다 조건을 검사해서 최소 비용을 만족하는 조합만 결과 리스트에 추가했습니다.
사전 순 정렬을 위해 List에는 문자열을 받도록 했습니다.
- 시간: `O(n*2^n)`
- 공간: `O(2^n)`
사용해야 할 자료구조와 변수가 많아, 중간에 꼬여서 많이 헷갈렸습니다.

[한재모 / BOJ 골드 4] 다이어트

---

5주차/jihee/BOJ_다이어트.java

식재료의 조합, 영양소 조건 체크 후 최소 비용 조합 찾는
완탐 + 백트래킹 문제
* 시간복잡도 : O(N × 2^N)
* 공간복잡도 : O(N × 2^N)
백트래킹을 복습할 수 있어서 좋았다!

[김지희 / BOJ 골드4] 다이어트

---

5주차/huiyeong/BOJ_다이어트.java

선택 여부에 따라 모든 조합을 탐색해야 하는 문제로, 백트래킹을 이용한 완전 탐색으로 접근했습니다.
- 시간복잡도 : O(2^N * NlogN)
- 공간복잡도 : O(N* C)
백트래킹에 대해서 다시 한 번 공부할 수 있는 기회였습니다.

[김희영 / BOJ 골드4] 다이어트

---

BOJ_사다리 조작.java

`정답이 3보다 큰 값이면 -1 출력` 해당 조건을 바탕으로, 가로선 개수 0부터 3까지 백트래킹을 각각 반복하며 최솟값을 구했습니다.
- 시간: 모르겠음..
- 공간: `O(H*N)`
시간 초과가 발생하여 최적화가 필요함을 인지했지만, 방향을 떠올리는 데 좀 걸렸습니다.

[한재모 / BOJ 골드3] 사다리 조작

---

5주차/semin/BOJ_사다리 조작.java

DFS를 이용해 사다리를 최대 3개까지 추가하며 모든 경우를 탐색했다.
현재 사다리 상태가 유효한지 check() 함수를 통해 확인했다.
시간복잡도: O((H×N)^3)
→ 사다리 3개까지 선택 가능한 모든 위치를 완전탐색한다.
공간복잡도: O(H×N)
→ 사다리 구조를 2차원 배열로 표현하여 관리했다.
문제 조건이 조금 까다롭게 느껴져서 사다리 상태를 어떻게 표현하면 좋을 지 해결하지 못하고 정답을 참고했다..

[박세민 / BOJ 골드3] 사다리 조작

---

5주차/jihee/BOJ_사다리조작.java

아직 정답 해결을 못해서.... 내일까지 다시 풀어보고 수정하겠습니다 ㅠ 
시간 복잡도 : O((H × N)^3)
공간 복잡도 : O(H × N)
조건이 많아서 까다롭다..

[김지희/ BOJ 골드3] 사다리 조작

---

5주차/huiyeong/BOJ_색종이 붙이기.java

백트래킹을 사용해야 한다는 건 알겠지만 도저히 성공하지 못 해서 일단 한 것까지 올립니다.
- 시간복잡도 : O(5^25)
- 공간복잡도 : O(1)
백트래킹은 정말 어렵습니다..

[김희영 / BOJ 골드2] 색종이 붙이기

---

5주차/jihee/BOJ_색종이붙이기.java

색종이를 붙이는 모든 경우의수를 탐색해야 되기 때문에 백트래킹으로 접근했다.
현재 좌표에서 색종이를 붙일 수 있는지 판단한 뒤, 붙이고 다음 좌표로 재귀 호출을 한다.
* 시간복잡도 : O(5^25) : 모든 색종이 조합을 재귀로 시도
* 공간복잡도 : O(1)
색종이를 붙이고 되돌리는 과정을 처음에 생각 못해서 좀 오래걸렸다..

[김지희 / BOJ 골드2] 색종이 붙이기

---

5주차/semin/Programers_거리두기 확인하기.java

5×5 대기실마다 P 위치에서 DFS를 통해 거리두기 위반 여부를 검사
2칸 이내의 탐색에서 P를 만나면 즉시 실패로 처리
시간복잡도: O(5×5×4^2) = O(500) 
-> DFS 깊이 제한 2
공간복잡도: O(5×5)
짧은 깊이의 DFS 문제였지만 조건 분기 처리와 상태 관리가 중요했다.

[박세민 / 프로그래머스 Lv.2] 거리두기 확인하기

---

5주차/semin/Programmers_멀쩡한 사각형.java

대각선이 그은 정사각형에서 제외되는 사각형 개수를 계산하기 위해,
1부터 w-1까지의 x좌표에 대해 직선과 겹치는 정사각형 수를 누적 계산하였다.
시간복잡도: O(w)
공간복잡도: O(1)
단순한 수학적 개념을 활용한 반복문이지만, 나누기 연산과 소수점 처리가 핵심이었다.

[박세민 / 프로그래머스 Lv.2] 멀쩡한 사각형

---

5주차/huiyeong/Programmers_멀쩡한 사각형.java

처음에는 직접 최대공약수를 구했는데 시간복잡도를 생각해보니 너무 커서 유클리드 호제법으로 방법을 바꿨습니다.
- 시간복잡도 : O(log min(w, h))
- 공간복잡도 : O(1)
시간복잡도를 항상 생각하게 되었습니다.

[김희영 / 프로그래머스 Lv.2] 멀쩡한 사각형

---

5주차/jihee/PG_멀쩡한 사각형.java

직사각형을 대각선으로 잘랐을 때 대각선이 지나가지 않아 멀쩡하게 남은 1×1 정사각형 개수를 구하는 문제
기울기를 이용해서 멀쩡한 사각형의 수를 누적
* 시간복잡도 : O(w)
* 공간복잡도 : O(1)
처음에 반복문으로 풀려다가 시간초과 발생할 것 같아서 풀이를 바꿨다. 시간복잡도를 항상 생각하면서 풀어야겠다.

[김지희/ 프로그래머스 Lv.2] 멀쩡한 사각형 

---

5주차/jaemo/PG_멀쩡한 사각형.java

[풀이](https://1eaf.site/cote/programmers_62048/)를 참고했습니다. 
- 시간: `O(logn)`
- 공간: `O(1)`
규칙을 찾고, 그 규칙을 수학적으로 풀어내는 과정이 너무 어려워요ㅠ

[한재모 / 프로그래머스 Lv.2] 멀쩡한 사각형

---

6주차/semin/BOJ_비드맨.java

전체 구슬 중 가장 많은 색상의 구슬 수가 나머지 구슬 수보다 크거나 같으면 해당 조건으로,
그렇지 않으면 홀짝 여부로 결과를 도출하였다.
시간복잡도: O(N)
공간 복잡도: O(1) 
전체 합과 최댓값 간의 관계를 수학적으로 해석하면 됐다.

[박세민 / BOJ 골드2] 비드맨

---

6주차/huiyeong/BOJ_비드맨.java

간단하게 구현했습니다.
- 시간 복잡도: O(N)
- 공간 복잡도: O(1)
간단하게 구현했습니다.

[김희영 / BOJ 골드2] 비드맨

---

6주차/jihee/BOJ_비드맨.java

구슬의 개수를 max > sum -max인 경우와 max <= sum - max인 경우를 나눠서 결과값을 도출했다.
* 시간복잡도 : O(N)
* 공간복잡도 : O(1)
간단하게 풀 수 있는 문제였다.

[김지희/ BOJ 골드2] 비드맨

---

6주차/semin/BOJ_Field Reduction.java

가장자리에 위치한 점들만 삭제했을 때 넓이가 바뀌므로,
최대 12개만 후보로 삼고 세 점을 골라 넓이의 최솟값을 계산했다.
시간복잡도: O(N log N + C^3)
공간복잡도: O(N)
완전 탐색이라도 후보를 잘 줄이면 충분히 최적화가 가능하다는 점을 느꼈다.

[박세민 / BOJ 골드3] Field Reduction

---

6주차/huiyeong/BOJ_Field Reduction (Silver).java

영향을 줄 수 있는 소들을 모두 고르는 방식으로 진행했습니다.
- 시간 복잡도: O(N log N + N × 조합 수)
- 공간복잡도 : O(N)
간단하게 구현했습니다.

[김희영 / BOJ 골드3] Field Reduction

---

6주차/jihee/BOJ_Field Reduction.java

* 최대 y값, 최소 x값, 최대 x값 최대 y값 삭제
* x좌표 담을 배열, y좌표 담을 배열
* x좌표 3개 y좌표 3개 모두 돌면서 삭제하기.
시간 복잡도: O(N log N)
공간복잡도 : O(N)
백트래킹으로 좌표를 모두 돌면서 삭제 후 최대값을 구해주었다.

[김지희 / BOJ 골드3] Field Reduction (Silver)

---

6주차/semin/BOJ_알파벳.java

문자는 중복 없이 한 번만 밟을 수 있는 조건을 만족시키기 위해 DFS(깊이 우선 탐색)와 백트래킹을 사용했다.
방문한 알파벳을 HashSet으로 관리하며, 사방 탐색을 통해 이동 가능한 모든 경로를 재귀적으로 확인한다.
탐색 과정에서 현재까지 밟은 알파벳 수를 카운트하며 최대값을 갱신했다.
시간 복잡도: O(4^N)
-> 최악의 경우 26개의 알파벳을 중복 없이 방문 가능하므로 4^26 수준의 재귀 호출이 일어날 수 있다.
공간 복잡도: O(N × M) + O(1)
->맵 저장용 2차원 배열과 알파벳 방문 여부를 위한 Set 사용.
DFS와 백트래킹의 조합으로 풀 수 있었다.

[박세민 / BOJ 골드4] 알파벳

---

6주차/huiyeong/BOJ_알파벳.java

모든 경로를 다 확인해야 하기 때문에 DFS로 했습니다.
- 시간복잡도 : O(4^L) 
L은 이동 가능한 칸 수입니다.
- 공간복잡도 : O(R * C) 
백트래킹을 간단하게 복습할 수 있는 기회였습니다.

[김희영 / BOJ 골드4] 알파벳

---

6주차/jihee/BOJ_알파벳.java

DFS + 백트래킹을 사용해서 풀었다. 상하좌우 4방향 이동하면서 방문하지 않은 알파벳이면 재귀 호출
* 시간복잡도 : O(4^26)
* 공간복잡도 : O(NxM)
* 
백트래킹을 복습할 수 있었다.

[김지희/ BOJ 골드4] 알파벳

---

6주차/semin/Progammers_문자열 압축.java

문자열 압축 결과의 최소 길이를 구하는 문제로, 압축 단위를 1부터 문자열 길이의 절반까지 변화시키며 시뮬레이션을 수행한다. 반복되는 문자열은 압축 단위 기준으로 그룹화하여 반복 횟수와 함께 압축하고, 이를 통해 가능한 모든 경우의 길이를 비교한다.
시간 복잡도: O(N^2), 압축 단위마다 문자열을 매번 슬라이싱하여 비교하고 압축 문자열을 생성함.
공간 복잡도: O(N), StringBuilder 사용.
반복되는 문자열 비교와 압축 단위 관리 등 기본적인 문자열 조작 능력을 점검할 수 있는 문제였다.

[박세민 / 프로그래머스 Lv.2] 문자열 압축

---

6주차/jihee/PG_문자열 압축.java

문자열을 1부터 N/2 길이까지의 단위로 잘라가며 압축을 한다.
반복 단위마다 압축 결과의 길이를 구하고, 그중 가장 짧은 길이를 정답으로 반환
* 시간 복잡도: O(N²)
* 공간 복잡도: O(N)
문자열의 끝부분을 처리하는게 중요했다.

[김지희/ 프로그래머스 Lv.2] 문자열 압축

---

6주차/huiyeong/Programmers_문자열 압축.java

간단한 구현문제라고 생각했습니다 
시간 복잡도를 조금이라도 줄이기 위해서 길이의 반이 넘어가면 겹치는 부분이 없기 때문에 검사를 하지 않으려고 반복문을 길이의 절반만 돌렸습니다.
- 시간 복잡도 : O(N^2)
- 공간 복잡도 : O(N)
간단하게 풀었습니다.

[김희영 / 프로그래머스 Lv.2] 문자열 압축

---

6주차/semin/Programmers_과제 진행하기.java

과제 시작 시간을 기준으로 정렬한 후, 큐를 통해 과제를 순차적으로 진행하며 중단된 과제는 스택에 저장한다. 다음 과제 시작 전 여유 시간이 있을 경우 스택에서 중단된 과제를 꺼내 이어서 진행한다.
시간 복잡도: O(N log N)
-> 시작 시간 기준 정렬
공간 복잡도: O(N)
-> 큐와 스택에 최대 N개의 과제가 저장
다른 사람들의 풀이를 참고하니 별도의 Node 클래스를 제작하여 데이터를 활용했었다. 다른 사람의 풀이를 공부해볼 필요가 있는 문제였다.

[박세민 / 프로그래머스 Lv.2] 과제 진행하기

---

6주차/huiyeong/Programmers_과제 진행하기.java

후입선출로 나와야 하기 때문에 스택을 사용해야겠다고 생각했습니다.
- 시간 복잡도 : O(N log N)
- 공간 복잡도 : O(N) 스택을 사용했기 때문입니다.
while문 처리부분에서 조건 문제로 조금 힘들었지만 잘 해결했습니다.

[김희영 / 프로그래머스 Lv.2] 과제 진행하기

---

6주차/jaemo/PG_과제 진행하기.java

LocalTime을 사용하여 각 과제별 시간 차이를 구해줬고, Stack으로 진행 중이던 과제를 복원하는 방식으로 풀었습니다.
- 시간: `O(NlogN)`
- 공간: `O(N)`
LocalTime의 메서드가 잘 기억이 나지 않았던 점이 시간을 많이 깎았던 것 같아요. 
이러한 날짜, 시간 문제가 나올 때를 대비해 관련 함수를 암기해야겠습니다.

[한재모 / 프로그래머스 Lv.2] 과제 진행하기

---

6주차/jihee/PG_과제 진행하기.java

과제 시간대로 정렬 후 새로운 과제 시간이 됐을 시 stack에 이전 과제를 넣어주는 방식으로 풀이
시간 복잡도 : O(N log N)
공간 복잡도 : O(N)
시간 조건 처리 때문에 문제 풀이가 꽤 오래걸렸습니다.

[김지희/ 프로그래머스 Lv.2] 과제 진행하기

---

7주차/semin/BOJ_벽 부수고 이동하기.java

BFS를 기반으로 벽을 부수지 않은 상태와 부순 상태를 구분해 3차원 배열로 최단 거리를 기록한다.
같은 위치라도 벽을 부쉈는지 여부에 따라 다른 경로가 가능하므로, 상태를 추가로 관리한다.
큐에 (x, y, 벽 부순 여부)를 함께 저장하며 최단 경로를 탐색했다.
시간 복잡도: O(N×M)
-> 각 위치에 대해 벽 부숨 여부(2가지 상태)로 방문하며 탐색함.
공간 복잡도: O(N×M×2)
-> 방문 배열을 3차원으로 사용하여 상태별 거리 저장.
벽을 한 번만 부술 수 있다는 조건이 상태 추가의 중요성을 일깨워주었다.
BFS에 조건부 상태를 함께 넣어 관리하는 것이 매우 효과적인 전략임을 다시 느꼈다.

[박세민 / BOJ 골드3] 벽 부수고 이동하기

---

7주차/jihee/BOJ_벽 부수고 이동하기.java

최단경로를 보고 bfs 풀이를 떠올렸습니다. 
방문 배열은 visited[x][y][broken]로 처리하였습니다. 
(x, y)에 벽을 부수지 않고 도달한 경우와 한 번 부수고 도달한 경우를 구분해서 처리했습니다.
* 시간 복잡도: O(N × M × 2)
* 공간 복잡도: O(N × M × 2)
벽 부순 상태를 관리하는게 좀 까다로워서 풀이가 오래걸렸습니다.

[김지희/ BOJ 골드 3] 벽 부수고 이동하기

---

7주차/jaemo/BOJ_말이 되고픈 원숭이.java

말처럼 이동한 각 횟수에 따라 방문 여부를 체크하기 위해 3차원 배열 사용하여 BFS를 수행했습니다.
- 시간: `O(WHK)`
- 공간: `O(WHK)`
이제는 상태 BFS에 감이 잡힌 듯 합니다.

[한재모 /BOJ 골드 3] 말이 되고픈 원숭이

---

7주차/semin/BOJ_말이 되고픈 원숭이.java

일반적인 4방향 이동과 K회 제한의 말 이동(8방향)을 모두 고려한 BFS를 수행한다.
상태는 (x, y, 말처럼 이동한 횟수)로 구성되며, 이를 3차원 배열로 방문 처리한다.
시간 복잡도: O(H×W×K)
-> 각 위치와 말 이동 횟수마다 한 번씩 탐색 가능.
공간 복잡도: O(H×W×K)
-> 3차원 거리 배열을 사용하여 상태별 거리 저장.
BFS와 조건부 상태 트래킹을 결합하는 문제 해결 능력을 강화할 수 있었다.

[박세민 /BOJ 골드 3] 말이 되고픈 원숭이

---

7주차/huiyeong/BOJ_말이 되고픈 원숭이.java

최단 경로 문제이기 때문에 BFS로 도전했습니다.
- 시간복잡도: O(H × W × K) 
- 공간복잡도: O(H × W × K)
말 이동 횟수 제한 때문에 어려웠습니다.

[김희영 /BOJ 골드 3] 말이 되고픈 원숭이

---

7주차/jihee/BOJ_말이 되고픈 원승이.java

BFS를 통해 큐에 담고, 일반 이동과 말 이동을 각각 조건에 맞게 탐색 한다.
시간 복잡도:  O(H × W × K)
공간 복잡도:  O(H × W × K)
말 점프 횟수를 관리하는게 까다롭게 느껴졌다.

[김지희/BOJ 골드 3] 말이 되고픈 원숭이 

---

7주차/huiyeong/BOJ_텀 프로젝트.java

결국 모든 경로를 탐색해야 하기 때문에 BFS말고 DFS로 해결했습니다.
- 시간복잡도:O(n)
- 공간복잡도:O(n)
조건 구현이 어려웠습니다.

[김희영 / BOJ 골드 3] 텀 프로젝트

---

7주차/jaemo/BOJ_텀 프로젝트.java

DFS로 각 학생이 선택한 방향으로 탐색한 끝에 사이클을 형성하는 경우, 이는 팀에 소속되었음을 의미합니다. 따라서 해당 경로의 학생들을 팀 소속으로 처리했습니다.
이미 팀이 된 학생은 다시 탐색하지 않도록 팀 소속 여부를 체크하여 중복 연산을 줄이고, 시간 초과를 방지했습니다.
- 시간: `O(T*n)` ~ `O(T*n^2)`
- 공간: `O(n)`
처음에 너무 어렵게 생각했는데, 어떤 자료구조를 이용할지 좀만 더 생각해보면 그렇게 어렵지 않게 풀 수 있는 것 같습니다.

[한재모 / BOJ 골드 3] 텀 프로젝트

---

7주차/semin/BOJ_텀 프로젝트.java

학생의 선택을 그래프로 보고, 각 정점에서 사이클 여부를 DFS 방식으로 탐색한다.
방문 시 탐색 시작 노드 번호를 기록하여 사이클 여부를 판별하고, 방문 상태를 분리 관리한다.
사이클에 포함된 학생은 따로 마킹해두고, 포함되지 않은 학생 수를 계산하여 출력한다.
시간 복잡도: O(N)
공간 복잡도: O(N)
상태값을 활용한 정교한 방문 처리 방식이 유용했다.

[박세민 / BOJ 골드 3] 텀 프로젝트

---

7주차/jihee/BOJ_텀 프로젝트.java

DFS를 통해 학생들이 사이클을 이루는지 확인합니다.
방문 중이면서 아직 DFS가 끝나지 않은 노드를 다시 방문하면, 사이클이 형성된 것으로 간주
시간복잡도: O(N)
공간복잡도: O(N)
방문 여부 배열과 팀 완성 여부 배열을 나눠서 체크하는게 중요한 문제였습니다.

[김지희 / BOJ 골드 3] 텀 프로젝트

---

7주차/semin/Programmers_마법의 엘리베이터.java

각 자리수에서 올림/내림을 선택하며 최소 이동 횟수를 구한다.
뒷자리부터 확인하며, 5일 경우 다음 자리수의 값에 따라 결정한다.
올림 시 상위 자릿수가 영향을 받으므로, storey++ 처리를 한다.
시간 복잡도: O(log_10(N))
공간 복잡도: O(1)
그리디 문제.
단순히 현재 자리수만 보지 않고, 다음 자리수까지 고려하며
자릿수마다 최소 연산을 선택하는 방식이 최적 결과를 보장하는 것을 확인했다.

[박세민 / 프로그래머스 Lv.2] 마법의 엘리베이터

---

7주차/jihee/PG_마법의 엘리베이터.java

자리수 뒤에서부터 반올림 체크하며 그리디로 간단하게 해결!
* 시간복잡도 : O(log₁₀N)
* 공간복잡도 : O(1)
금방 풀 수 있는 문제였습니다.

[김지희 / 프로그래머스 Lv.2] 마법의 엘리베이터

---

7주차/jaemo/PG_마법의 엘리베이터.java
7주차/jaemo/PG_타겟 넘버.java

처음에는 BFS로 풀려다가, 시간 복잡도를 고려해 수학적으로 그리디하게 푸는 방식을 택했습니다.
각 정수마다 최적의 해가 무엇인지 그려보며, 반복문을 통해 구현했습니다.
- 시간: `O(logN)`
- 공간: `O(1)`
오랜만에 그리디 알고리즘을 공부할 수 있었습니다. 그리디는 조금만 삐끗하면 혼란스러운 것 같아요
---
입력 범위가 작은 점을 고려해 DFS로 모든 경우의 수를 탐색하도록 했습니다.
- 시간: `O(2^N)`
- 공간: `O(N)`
기본적인 dfs 문제였던 것 같습니다.

[한재모 / 프로그래머스 Lv.2] 마법의 엘리베이터 | [한재모 / 프로그래머스 Lv.2] 타겟 넘버

---

7주차/jihee/PG_타겟 넘버.java

백트래킹으로 - +인 경우를 모두 탐색하며 정답 값을 체크하였습니다.
* 시간복잡도 : O(2ⁿ) -> 각 숫자마다 + - 두갈래 탐색
* 공간복잡도 : O(n)
* 
dfs의 기초적인 문제라 간단하게 풀 수 있었습니다.

[김지희 / 프로그래머스 Lv.2] 타겟 넘버

---

8주차/semin/BOJ_이분 그래프.java

BFS를 활용하여 인접 노드를 두 개의 그룹(0, 1)으로 번갈아가며 색칠한다.
각 정점에서 인접 노드가 같은 그룹일 경우 이분 그래프가 아님을 판별한다.
모든 정점에서 BFS를 돌려 연결되지 않은 컴포넌트도 처리한다.
- 시간 복잡도: O(V + E)
-> 모든 정점과 간선을 한 번씩 탐색한다.
- 공간 복잡도: O(V + E)
-> 그래프와 방문 상태 저장에 필요하다.
-

[박세민 / BOJ 골드 4] 이분 그래프

---

8주차/jihee/BOJ_이분 그래프.java

DFS를 이용해 각 정점을 번갈아가며 두 그룹으로 나누는 방식으로 그래프를 탐색합니다.
시간 복잡도 : O(K * (V + E))
공간복잡도
인접 리스트 list: O(V + E)
방문 배열 visited: O(V)
-> O(V + E)
그룹을 번갈아 지정하며 재귀로 진행한다는 걸 파악하는게 중요한 문제였습니다.

[김지희/ BOJ 골드 4] 이분 그래프 

---

8주차/huiyeong/BOJ_이분 그래프.java

모든 정점을 탐색해야 하기 때문에 BFS로 접근했습니다.
- 시간 복잡도: O(V + E)
- 공간 복잡도: O(V + E) + O(V)

[김희영/ BOJ 골드 4] 이분 그래프

---

8주차/jaemo/BOJ_빙산.java

전체 로직을 `모든 빙산이 녹았는지 확인`, `2개 이상으로 분리되었는지 확인`, `빙산 녹이기` 3단계로 나누었고, 분리 여부 확인은 BFS를 사용해 구현했습니다.
- 시간: `O(NM)`
- 공간: `O(NM)`
어렵지 않은 BFS 활용 구현이었습니다.

[한재모 / BOJ 골드 4] 빙산

---

8주차/semin/BOJ_트리 지름.java

임의의 노드에서 가장 먼 노드를 찾고, 그 노드에서 다시 가장 먼 거리까지 DFS를 수행한다.
가장 먼 거리 값이 트리의 지름이 된다.
- 시간 복잡도: O(N)
- 공간 복잡도: O(N)
트리 구조의 다양한 탐색 패턴을 익힐 수 있는 문제였다.

[박세민 / BOJ 골드 4] 트리의 지름

---

8주차/semin/Programmers_리코쳇 로봇.java

BFS를 활용하여 미로에서 'R'에서 시작해 'G'로 가는 최단 거리를 탐색한다.
장애물 'D'를 피하며, 한 방향으로 끝까지 미끄러지는 방식으로 이동한다.
도착 지점 'G'에 도달하면 해당 지점까지의 이동 횟수를 반환한다.
- 시간 복잡도: O(N×M×4)
- 공간 복잡도: O(N×M)
if문 안에 조건이 길어져서 해당 문장을 하나의 메소드로 만들었다.

[박세민 / 프로그래머스 Lv.2] 리코쳇 로봇

---

8주차/huiyeong/Programmers_리코쳇 로봇.java

저번에 했던 것과 비슷하지만 조금 다르게 진행했습니다.
저번 문제는 각각 BFS를 실행하면 되는 문제였지만 이번 문제는 이어서 실행해야 합니다.
- 시간복잡도 : 
- 공간복잡도 :
저번에 도전했던 문제라 접근방식에 대해서는 쉽게 느꼈습니다.

[김희영 / 프로그래머스 Lv.2] 리코쳇 로봇

---

8주차/jihee/PG_리코쳇로봇.java

시작 지점 'R'을 찾아 BFS 탐색을 시작하고 'G'에 도달할 때까지 최소 이동 횟수를 탐색
* 시간복잡도 : O(N × M)
* 공간복잡도 : O(N × M)
전에 풀었던 문제와 비슷해서 BFS로 접근해서 어렵지 않게 풀 수 있었다.

[김지희/ 프로그래머스 Lv.2] 리코쳇 로봇

---

8주차/semin/Programmers_줄 서는 방법.java

K번째 순열을 찾기 위해 팩토리얼 정보를 이용한 수학적 접근을 했다.
각 자리의 수를 직접 계산하여 리스트에서 제거하고 결과를 구성했다.
남은 수는 역순으로 붙여 최종 순열을 완성한다.
시간 복잡도: O(N^2)
공간 복잡도: O(N)

[박세민 / 프로그래머스 Lv.2] 줄 서는 방법

---

8주차/jaemo/PG_리코쳇 로봇.java
8주차/jaemo/PG_줄 서는 방법.java

BFS를 활용해 최소 이동 횟수를 구하는 방식으로 풀었습니다. 단, 장애물을 만날 때까지 이동하도록 했습니다.
- 시간: `O(4NM)`
- 공간: `O(NM)`
이동하는 것만 주의해서 풀면 어렵지 않은 문제인 듯 합니다.
---
dfs로 순열을 만드는 방식은 시간 초과가 발생하기 때문에, 팩토리얼을 활용한 수학적 접근으로 직접 k번째 순열을 계산해야 합니다.
- 시간: `O(n^2)`
- 공간: `O(n)`
수학적으로 접근해야 풀 수 있는 문제로, 생각보다 쉽지 않았던 것 같습니다.

[한재모 / 프로그래머스 Lv.2] 리코쳇 로봇 | [한재모 / 프로그래머스 Lv.2] 줄 서는 방법

---

9주차/jaemo/BOJ_가장 가까운 공통 조상.java
9주차/jaemo/BOJ_나무 위의 빗물.java

각 노드의 부모 노드를 담는 배열을 정의하고, 해당 배열을 통해 조상 노드들을 탐색합니다. 
두 노드의 조상을 탐색한 후 교집합을 구하고, 집합에서 가장 먼저 찾은 노드를 반환합니다.
- 시간: `O(TN^2)`
- 공간: `O(N)`
부모 노드는 하나라는 트리의 특징을 알고 있어, 배열로 쉽게 풀 수 있었습니다.
---
물이 동일 확률로 계속 흐르다 보면, 결국 리프 노드에만 고이게 될 것입니다. 따라서, 기댓값이 리프 노드의 수만 세어 `W / 리프 수`를 구하면 평균 기댓값이 됩니다.
- 시간: `O(N)`
- 공간: `O(N)`
물이 흐르는 확률이 동일하다는 점만 잘 캐치하면 어렵지 않은 문제인 듯 합니다.

[한재모 / BOJ 골드 4] 가장 가까운 공통 조상 | [한재모 / BOJ 골드 5] 나무 위의 빗물

---

9주차/jihee/BOJ_가장 가까운 공통 조상.java

1. a의 모든 조상 노드를 visited 배열에 표시하며 루트까지 거슬러 올라간다.
2. b도 부모를 따라 루트까지 올라가면서, visited[b] == true인 최초의 노드를 찾는다.
해당 노드가 두 노드의 가장 가까운 공통 조상이다.
시간 복잡도: O(N)
공간 복잡도: O(N)

[김지희/ BOJ 골드 4] 가장 가까운 공통 조상

---

9주차/semin/BOJ_나무 위의 빗물.java

입력으로 주어진 트리를 인접 리스트로 구성한 후, 리프 노드의 개수를 세어 총 가중치(W)를 리프 노드 개수로 나눈 값을 출력한다.
- 시간 복잡도: O(N)
- 공간 복잡도: O(N)
단순한 트리 순회 없이도 간선 수만으로 리프 노드를 판별할 수 있어 효율적이다.

[박세민 / BOJ 골드 5] 나무 위의 빗물

---

9주차/jihee/BOJ_회사문화1.java

전위 순회를 사용하여 부모의 값을 자식에게 누적 전달하는 방식, DFS로 전위 순회를 구현하였다.
시간 복잡도: O(N + M)
공간 복잡도: O(N)
트리 구조를 배열로 나타내고 DFS로 간단하게 누적 값을 전파할 수 있어서 어렵지 않게 풀 수 있었다.

[김지희/ BOJ 골드 4] 회사 문화 1

---

9주차/semin/BOJ_회사 문화 1.java

문제는 트리의 루트 노드에서 자식 노드로 전파되는 누적 값을 계산하는 것이다.
입력으로 주어진 부모-자식 관계를 트리로 구성하고, 보상 정보를 루트부터 DFS 방식으로 누적한다.
Stack을 사용한 반복 DFS로 모든 노드에 대해 누적값을 계산한 후 출력한다.
- 시간 복잡도: O(n + m)
- 공간 복잡도: O(n)
반복 DFS를 통해 누적 보상을 효율적으로 계산할 수 있다는 점이 인상적이다.
Java에서 Stack 대신 ArrayDeque를 사용하는 것이 성능상 더 좋으며, 스트림 API로 가독성 높은 출력도 가능함을 확인했다.

[박세민 / BOJ 골드 4] 회사 문화 1

---

9주차/jaemo/BOJ_회사 문화 1.java

트리를 구성한 후 루트 노드(1번)부터 DFS를 통해 누적 박수 값을 구했습니다.
- 시간: `O(N)`
- 공간: `O(N)`
트리 기반 누적 문제를 DFS로 해결할 수 있었습니다.

[한재모 / BOJ 골드 4] 회사 문화 1

---

9주차/jihee/PG_표현 가능한 이진트리.java

트리 루트를 기준으로 좌우 트리를 재귀로 순회하였다.
* 시간복잡도 :  O(K × L) 
* 공간복잡도 : O(L)
접근 방식이 바로 떠오르지 않아서 어려웠다. 블로그 참고해서 풀었습니다..

[김지희 / 프로그래머스 Lv.3] 표현 가능한 이진트리

---

9주차/semin/Programmers_섬 연결하기.java

최소 신장 트리를 구성하기 위해 크루스칼 알고리즘을 사용했다.
간선을 비용 기준으로 정렬하고, Union-Find로 사이클 여부를 판별하며 선택한다.
비용이 낮은 간선부터 연결해 전체 연결 비용을 최소화한다.
시간 복잡도: O(E log E)
공간 복잡도: O(N)

[박세민 / 프로그래머스 Lv.3] 섬 연결하기

---

9주차/jaemo/PG_섬 연결하기.java

비용이 적은 간선부터 선택하면서 사이클이 생기지 않도록 유니온 파인드를 활용해야 했습니다.
- 시간: `O(E log E)`
- 공간: `O(N)`

[한재모 / 프로그래머스 Lv.3] 섬 연결하기

---

10주차/semin/BOJ_소수 부르기 게임.java

두 정수 구간에서 소수를 구하고, 공통 소수의 개수 및 전체 개수를 비교해 결과를 출력한다.
에라토스테네스의 체로 소수를 판별하고, Set을 이용해 교집합 계산을 효율화했다.
- 시간 복잡도: O(n log log n + r1 + r2)
-> 소수 구하기와 두 범위 순회
- 공간 복잡도: O(n)
-> 수 여부 배열, HashSet 2개
나는 이런 문제를 왜 골랐을까

[박세민 / BOJ 실버 3] 소수 부르기 게임

---

9주차/jihee/PG_섬 만들기.java
9주차/jihee/PG_표현 가능한 이진트리.java

이 문제는 모든 섬을 최소 비용으로 연결하는 MST 문제
시간 복잡도 : O(E log E)
공간 복잡도 O(N)
사이클 없이 연결하는 개념이 좀 헷갈렸습니다. Kruskal 알고리즘을 익힐수 있었습니다.

[김지희 / 프로그래머스 Lv.3] 섬 연결하기

---

10주차/BOJ_공유기 설치.java
9주차/jihee/BOJ_회사문화1.java
9주차/jihee/PG_섬 만들기.java
9주차/jihee/PG_표현 가능한 이진트리.java

가장 인접한 두 공유기 사이의 최소 거리를 최대한 크게 만드는 이진 탐색 문제
시간 복잡도: O(N log N)
공간 복잡도: O(N) 
오랜만에 이진탐색 개념 복습할 수 있었습니다.

[김지희/ BOJ 골드 4] 공유기 설치

---

10주차/huiyeong/Programmers_영어 끝말잇기.java

[김희영 / 프로그래머스 Lv.2] 영어 끝말잇기

---

10주차/jihee/BOJ_평범한 배낭.java

총 무게가 K를 넘지 않으면서, 물건을 한 번만 사용할 수 있고, 가치의 합이 최대가 되도록 선택
dp[i][j]: i번째 물건까지 고려했을 때, 배낭의 최대 허용 무게가 j일 때 얻을 수 있는 최대 가치
시간 복잡도: O(N * K)
공간 복잡도: O(N * K)
dp를 복습할 수 있었다.

[김지희/ BOJ 골드 5] 평범한 배낭

---

9주차/jihee/BOJ_단지번호붙이기.java

상, 하, 좌, 우 방향으로만 연결된 집(1)을 같은 단지로 간주하고 dfs를 통해 순회
시간 복잡도:  O(N^2)
공간 복잡도: O(N^2)

[김지희 / 실버1] 단지번호붙이기

---

10주차/semin/BOJ_상범빌딩.java

3차원 배열을 이용해 건물 내 위치를 L×R×C 형태로 표현하고 BFS로 최단 탈출 경로를 탐색한다.
시작점 S에서 출발하여 상하좌우위아래 6방향을 탐색하며 graph를 갱신한다.
도착점 E에 도달하면 걸린 시간을 출력하고, 도달하지 못하면 "Trapped!"를 출력한다.
- 시간 복잡도: O(L×R×C)
- 공간 복잡도: O(L×R×C) 
초기값 설정, 입력 처리, 줄바꿈 처리 등 입출력 예외에 유의해야 한다.

[박세민 / BOJ 골드 5] 상범 빌딩

---

10주차/huiyeong/BOJ_N과 M (1).java
10주차/huiyeong/BOJ_영단어 암기는 괴로워.java

sort로 해서 정렬 우선 순위를 잘 푸는게 중요하다고 생각했습니다. System.out.println 을 활용해서 출력할 경우 시간초과가 돼서 StringBuilder를 활용해서 출력했습니다.
- System.out.println()
호출할 때마다 콘솔 I/O가 발생
내부적으로 PrintStream → flush() 또는 버퍼 관리
많은 호출이 있으면 매번 시스템 콜(I/O 오버헤드) 발생
- StringBuilder
메모리 상에서 문자열을 append()만 함 (빠름)
마지막에 한 번만 System.out.print(sb) → I/O 1회
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
간단하게 풀면서 자바 문법에 대해서 다시 공부할 수 있는 기회였습니다.
문제를 봤을 때 다시 되돌아와야 하기 때문에 백트래킹이라는 걸 알았습니다. 가장 기초적인 백트래킹 문제였습니다.
- 시간복잡도 : O(N!/(N−M)!)
- 공간복잡도 : O(N+M)
백트래킹에 대해서 다시 한 번 공부할 수 있는 기회였습니다.

[김희영 / BOJ 실버 3] 영단어 암기는 괴로워 ,  [김희영 / BOJ 실버 3] N과 M (1) 

---

11주차/semin/BOJ_K번째 수.java

이분 탐색으로 k번째 수가 B배열 어디쯤 있는지를 추정하고, 중복 포함 개수를 계산하여 범위를 좁힌다.
mid값 이하의 수가 몇 개인지를 반복 계산하며 조건을 만족하는 최소값을 찾는다.
시간 복잡도: O(n log k) 
공간 복잡도: O(1)

[박세민 / BOJ 골드 1] K번째 수

---

11주차/huiyeong/BOJ_사냥꾼.java

완전탐색하는게 메모리상 불가능해서 이분탐색을 하였습니다.
- 시간복잡도 : O(M log M + N log M)
정렬이 O(M log M) 이고 이분탐색이 O(N log M)입니다.
- 공간복잡도 : O(M)
보통 점(데이터 양이 적고 고정된 느낌이 강한 것)을 기준으로  그 외에 것을 비교하는 식이였다고면 이건 다른 걸 기준으로 점을 비교하는 식이여서 새로웠습니다.

[김희영 / BOJ 골드 4] 사냥꾼

---

11주차/semin/BOJ_숫자구슬.java

구슬을 m개의 그룹으로 나눌 때 각 그룹의 합이 특정 값을 넘지 않도록 이분 탐색을 적용했다.
이때 가능한 최대 그룹합을 찾기 위해 possible() 함수로 조건 검사를 반복한다.
각 그룹의 구슬 수를 기록하며 적절한 분할 여부를 판단한다.
시간 복잡도: O(n log(100n))
공간 복잡도: O(n + m)

[박세민 / BOJ 골드 2] 숫자구슬

---

11주차/jaemo/PG_인사고과.java

근무 태도는 내림차순, 동료 평가는 오름차순으로 정렬하여 인센티브 대상자를 효율적으로 필터링하도록 합니다. 필터링된 대상들을 기반으로 완호의 석차를 구합니다.
- 시간: `O(nlogn)`
- 공간: `O(1)`
정렬 기준이 효율성을 좌우한다는 부분을 느꼈습니다.

[한재모 / 프로그래머스 Lv.3] 인사고과

---

11주/semin/Programmers_인사고과.java

자기 평가 점수와 동료 평가 점수를 기준으로 정렬한 후, 완호보다 모두 높은 점수를 받은 지원자를 제외하고 등수를 계산한다.
조건에 따라 탈락 여부를 먼저 판단한 뒤, sum 기준으로 등수를 매긴다.
정렬 시 자기평가 점수는 내림차순, 동료평가는 오름차순으로 하여 탐색의 효율성을 높였다.
- 시간 복잡도: O(n log n) - 지원자 점수 정렬
- 공간 복잡도: O(1) - 추가적인 배열이나 자료구조 사용 없이 변수만 사용

[박세민 / 프로그래머스 Lv.3] 인사고과

---

11주차/semin/Programmers_요격 시스템.java

미사일 구간을 시작 지점 기준으로 정렬한 뒤, 요격 가능한 구간의 겹침 여부를 통해 새로운 요격 횟수를 결정한다.
겹치는 구간이 유지되는 동안 요격 구간을 갱신하며, 겹치지 않으면 요격 수를 증가시킨다.
그리디하게 최소 요격 횟수를 유지하는 방식으로 풀 수 있다.
- 시간 복잡도: O(n log n)
- 공간 복잡도: O(1) 
겹치는 구간을 갱신하는 로직이 핵심이었으며, 정렬 후 탐색이라는 그리디 기본 전략을 적용했다.

[박세민 / 프로그래머스 Lv.2] 요격 시스템

---

11주차/jaemo/PG_요격 시스템.java

각 미사일의 개구간 끝점 기준 오름차순 정렬 후, 현재 미사일이 커버하지 못하는 구간이 나오면 새 미사일을 발사합니다.
- 시간: `O(nlogn)`
- 공간: `O(1)`

[한재모 / 프로그래머스 Lv.2] 요격 시스템

---

11주차/jihee/PG_요격 시스템.java

끝나는 지점 기준 오름차순 정렬 후, 현재 요격 지점 이후에 시작하는 타겟이 나오면 새로운 미사일 발사
시간: O(N log N) 
공간: O(1)
그리디로 어렵지 않게 풀 수 있었다.

[김지희/ 프로그래머스 Lv.2] 요격 시스템

---

11주차/huiyeong/Programmers_요격 시스템.java
11주차/huiyeong/Programmers_인사고과.java

그리디
- 시간복잡도 : O(N log N)
- 공간복잡도 : O(1)
정렬만 해주면 쉽게 풀 수 있다고 생각했습니다.
탐색에 다양한 조건이 추가된 문제였습니다.
- 시간복잡도 : O(N log N)
- 공간복잡도 :  O(N)
다양한 조건을 구현하기 어려웠습니다.

[김희영 / 프로그래머스 Lv.2] 요격 시스템 , [김희영 / 프로그래머스 Lv.3] 인사고과

---

12주차/semin/Programmers_실패율.java

각 스테이지에 머물러 있는 사용자 수를 기반으로 실패율을 계산하고, 실패율이 높은 순서대로 스테이지를 정렬한다.
배열 count로 각 스테이지 도전자 수를 누적하고, fails 배열로 실패율을 저장한다.
정렬 대신 반복적으로 최대 실패율을 찾아 정답 배열에 순차적으로 담는다.
시간 복잡도: O(N²) 
공간 복잡도: O(N)

[박세민 / 프로그래머스 Lv.1] 실패율

---

12주차/jihee/PG_실패율.java

각 스테이지별로 클리어한사람, 클리어하지못한사람을 체크한 후, 실패율 기준으로 정렬한다.
시간복잡도 : O(N + K log K)
공간복잡도 : O(N + K)
total > 0 인 경우일때만 list에 값을 넣어줘서 런타임에러가 발생했다. 코드를 꼼꼼하게 살펴봐야겠다.

[김지희/ 프로그래머스 Lv.1] 실패율

---

12주차/semin/Programmers_방문 길이.java

문자는 방향을 의미하며, 현재 좌표에서 명령에 따라 이동해 간 경로를 기록한다.
HashSet을 사용해 이동한 경로를 문자열로 저장하고, 중복 이동은 제외한다.
왕복 경로를 고려해 양방향 모두 기록하며, 전체 길이의 절반을 반환한다.
시간 복잡도: O(n)
공간 복잡도: O(n)

[박세민 / 프로그래머스 Lv.2] 방문 길이

---

12주차/huiyeong/Programmers_올바른 괄호.java

스택을 이용해서 간단하게 해결했습니다.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)

[김희영 / 프로그래머스 Lv.2] 올바른 괄호

---

12주차/jaemo/PG_큰 수 만들기.java

k개의 숫자를 버려 가장 큰 수를 만들기 위해서는, 맨앞자리 수가 가장 커야 합니다.
stack을 이용해 k개의 숫자를 버리면서 가장 큰 숫자가 앞에 오도록 했고, 마지막에는 스택에서 꺼낸 숫자들을 뒤집어 나열했습니다.
- 시간: `O(N)`
- 공간: `O(N)`
처음에는 복잡하게 생각하여 범위마다 탐색하려 했지만, 스택을 이용해 앞에서부터 버리면서 푸는게 훨씬 간단하고 효율적임을 깨달았습니다.

[한재모 / 프로그래머스 Lv.2] 큰 수 만들기

---

12주차/semin/Programmers_올바른 괄호.java

문자열 내 괄호의 유효성을 판단하기 위해 스택을 활용한다.
여는 괄호 (는 스택에 추가하고, 닫는 괄호 )는 짝이 맞는지 확인해 제거한다.
모든 문자 처리 후 스택이 비어 있으면 올바른 괄호 문자열로 판단한다.
시간 복잡도: O(n)
공간 복잡도: O(n)

[박세민 / 프로그래머스 Lv.2] 올바른 괄호

---

12주차/jihee/PG_올바른괄호.java

'(' 문자가 나오면 stack에 추가하고, ')'문자일시 괄호를 꺼내준다.
사이즈가 0일 때 ')'괄호가 나오거나 stack사이즈가 0보다 클 경우 false를 반환한다
* 시간복잡도 :  O(N)
* 공간복잡도 :  O(N)

[김지희/ 프로그래머스 Lv.2] 올바른 괄호

---

12주차/huiyeong/Programmers_주식가격.java

크기에 따라서 진행되기 때문에 스택을 이용했습니다.
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)

[김희영 / 프로그래머스 Lv.2] 주식가격

---

12주차/jaemo/PG_주식가격.java

가격이 유지되거나 올라갈 때는 스택에 넣고, 떨어짐을 확인했을 때 스택에서 그 순간의 가격보다 높은 요소를 모두 꺼냅니다.
꺼낸 요소들 각각의 유지 시간을 계산하여 정답 배열에 넣습니다.
마지막에는, 끝까지 떨어지지 않은, 즉 스택에 남은 요소 또한 모두 꺼내 시간을 계산합니다.
- 시간: `O(N)`
- 공간: `O(N)`
문제 이해 자체가 어려웠습니다..

[한재모 / 프로그래머스 Lv.2] 주식가격

---

12주차/semin/Programmers_크레인 인형뽑기 게임.java

크레인으로 인형을 뽑는 순서를 따라 2차원 보드를 순회하며 스택에 담고, 같은 인형이 연속되면 제거한다.
moves 배열의 각 값은 열을 의미하며, 해당 열에서 가장 위에 있는 인형을 선택한다.
스택의 최상단과 현재 인형이 같으면 제거하고, 다르면 스택에 넣는다.
시간 복잡도: O(m × n) 
공간 복잡도: O(n)

[박세민 / 프로그래머스 Lv.1] 크레인 인형뽑기 게임

---

12주차/huiyeong/Programmers_크레인 인형뽑기 게임.java

맨위에랑 똑같은 경우 없어지는 것이기 때문에 스택을 생각했습니다.
- 시간복잡도 : O(M × N)
- 공간복잡도 : O(M)

[김희영 / 프로그래머스 Lv.1] 크레인 인형뽑기 게임

---

12주차/jihee/PG_크레인 인형뽑기.java

동일한 숫자가 올 경우 사라지기 때문에 stack을 사용해서 풀이하였다.
시간복잡도 : O(M × N)
공간복잡도 : O(M)

[김지희/ 프로그래머스 Lv.1] 크레인 인형뽑기 게임

---

13주차/jaemo/PG_표 편집.java

이전 행과 다음 행에 대한 정보는 담는 각 배열을 통해 각 행의 이전/다음 인덱스를 추적합니다.
삭제 명령 시 배열에서 연결을 끊고, 그 행에 대한 정보를 stack에 저장합니다.
복구 명령 시 stack에서 최근 행에 대한 정보를 꺼내고, 다시 배열에서 연결을 맺습니다.
- 시간: `O(N)` 
- 공간: `O(N)`
효율성 측면에서 어떻게 연결을 맺고 끊을지 생각하는게 어려웠습니다.

[한재모 / 프로그래머스 Lv.3] 표 편집

---

13주차/semin/Programmers_표 편집.java

이 문제는 연결 리스트처럼 위아래 행을 추적하며 삭제 및 복원 명령을 처리하는 시뮬레이션 문제이다.
삭제 시 현재 인덱스를 스택에 저장하고, 복원 시 연결을 다시 이어준다.
각 명령을 처리한 뒤, 삭제된 행은 'X', 남은 행은 'O'로 표시해 문자열을 구성한다.
- 시간 복잡도: O(m × x): 명령어 m개 중 U/D는 최대 x번 반복, C/Z는 O(1)
- 공간 복잡도: O(n): 위/아래 인덱스 배열과 삭제 스택 저장 공간 사용
다른 답안을 참고해서 공부했을 정도로 조금 까다로웠다..!

[박세민 / 프로그래머스 Lv.3] 표 편집

---

13주차/semin/BOJ_요세푸스 문제.java

요세푸스 문제를 큐를 활용한 시뮬레이션 방식으로 해결하였다.
K번째 사람을 제거하면서 순서를 저장하고, 마지막 남은 사람까지 반복한다.
큐를 순환시켜 원하는 순서대로 제거된 요소를 StringBuilder에 기록한다.
- 시간 복잡도: O(NK): 각 요소를 최대 K번 순환하며 제거
- 공간 복잡도: O(N): 큐와 출력 문자열을 위한 공간 사용
큐의 순환을 활용하면 요세푸스 순열을 쉽게 구현할 수 있다는 점이 인상적이다.

[박세민 / BOJ 실버 4] 요세푸스 문제

---

13주차/jihee/BOJ_요세푸스문제.java

1부터 N까지 숫자를 삽입한 후,
매번 M-1개의 숫자를 큐의 뒤로 보낸 다음 M번째 숫자를 제거하며 출력
- 시간복잡도 : O(N × M)
- 공간복잡도 : O(N)
큐로 간단하게 풀 수 있었다.

[김지희/ BOJ 실버 4] 요세푸스 문제

---

14주차/semin/Programmers_오픈채팅방.java

Enter/Leave 로그를 리스트에 저장하고, 유저 ID별 닉네임은 Map에 기록해 관리한다.
최종 출력 시에는 저장된 ID를 통해 최신 닉네임으로 결과 메시지를 변환한다.
닉네임 변경(Change)은 기록하지 않고 Map만 갱신한다.
시간 복잡도: O(N): 입력 기록 한 번 순회, 결과 리스트 한 번 순회
공간 복잡도: O(N): 로그 리스트, ID-Nickname Map, 출력 배열 등

[박세민 / 프로그래머스 Lv.2] 오픈채팅방

---

14주차/jihee/PG_베스트앨범.java
14주차/jihee/PG_오픈채팅방.java

같은 브랜치에 푸시해버려서 한번에 적었습니다..!😥
Enter, Leave에 해당하는 메시지를 hashMap 에서 닉네임을 조회해 출력 형식에 맞게 생성
- 시간복잡도 :O(n)
- 공간복잡도 : O(n)
장르별 총 재생 수 계산하고, hashmap에 장르별로 곡의 인덱스와 재생 수 저장한다. 가장 인기 있는 장르 순으로 정렬한다.
- 시간복잡도 : O(N + G)
- 공간복잡도 : O(N + G)

[김지희 / 프로그래머스 Lv.2] 오픈채팅방, [김지희 / 프로그래머스 Lv.3] 베스트앨범

---

14주차/huiyeong/Programmers_베스트앨범.java

생각해야 하는 조건이 많아 복잡했지만 다른 알고리즘을 쓸 필요없이 구현 문제라 어떤 방식으로 데이터를 저장해야 할지 가장 많이 고민했습니다.
- 시간복잡도 : O(N log N)
- 공간복잡도 : O(N)

[김희영 / 프로그래머스 Lv.3] 베스트앨범

---

14주차/jaemo/PG_길 찾기 게임.java
14주차/jaemo/PG_다단계 칫솔 판매.java
14주차/jaemo/PG_양과 늑대.java

한 명의 판매원은 한 명 이하의 추천인만 존재하기에, 조직 구조를 Map으로 표현했습니다.
그리고 seller 배열을 순회하며 각각 dfs를 돌렸습니다.
- 시간복잡도 : `O(NlogM)` (N: seller 배열, M: amount 정수값)
- 공간복잡도 : `O(N)`
map을 이용하여 어렵지 않게 풀 수 있는 문제인 것 같습니다.
---
먼저 모든 경우의 수를 탐색하는 방식으로 풀었으며, 부모 노드로 되돌아가는 선택지도 있기에 방문 후보 list를 정의했습니다.
- 시간복잡도 : `O(N*2^N)`
- 공간복잡도 : `O(N^2)`
방문 후보 List를 다음 재귀 호출에 그대로 전달하면서 문제가 발생했고, 객체의 경우 주소가 복사된다는 점을 주의해야겠다고 느꼈습니다.
---
좌표값들을 y값 기준 내림차순, x값 기준 오름차순으로 정렬한 후 이진 트리를 만들었습니다. 
그리고나서 전위 순회와 후위 순회 각각의 결과를 2차원 배열로 합쳐 반환하도록 했습니다.
- 시간복잡도 : `O(N^2)`
- 공간복잡도 : `O(N)`
이진 트리와 전/후위 순회 구현 방법을 상기시킬 수 있었습니다.

[한재모 / 프로그래머스 Lv.3] 다단계 칫솔 판매 | [한재모 / 프로그래머스 Lv.3] 양과 늑대 | [한재모 / 프로그래머스 Lv.3] 길 찾기 게임

---

14주차/jihee/BOJ_퇴사2.java

dp로 현재 날짜에 기록된 금액 ,지금까지 누적금액 + 현재 날짜 금액 중 더 큰 금액 저장하여 최대 금액을 계산하였습니다.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)

[김지희 / 프로그래머스 Lv.2] 퇴사2

---

14주차/huiyeong/Programmers_혼자서 하는 틱택토.java

[김희영 / 프로그래머스 Lv.2] 혼자서 하는 틱택토

---

15주차/semin/BOJ_이중 우선순위 큐.java

TreeMap을 활용하여 정렬된 상태에서 삽입(I)과 삭제(D)을 빠르게 수행했다.
각 숫자의 개수를 map에 저장하여 중복 원소 처리도 가능하게 했다.(TreeSet 대신 TreeMap 사용하게 된 이유)
가장 큰 값과 가장 작은 값을 효율적으로 조회하기 위해 lastKey()와 firstKey()를 사용했다.
- 시간복잡도: O(KlogN)
- 공간복잡도: O(N)

[박세민 / BOJ 골드 4] 이중 우선순위 큐

---

15주차/semin/BOJ_보석 도둑.java

보석은 무게 기준으로, 가방은 용량 기준으로 정렬한 후, 가능한 보석을 우선순위 큐에 저장했다.
각 가방마다 담을 수 있는 최대 가치의 보석을 선택하여 총 가치를 최대화한다.
pq를 활용해 가치가 높은 보석부터 효율적으로 선택했다.
- 시간 복잡도: O(N log N)+O(K log K)+O(log N) = O(N + K log N)
- 공간 복잡도: O(N + K)

[박세민 / BOJ 골드 2] 보석 도둑

---

15주차/jihee/BOJ_욕심쟁이 판다.java
15주차/jihee/BOJ_출근경로.java

각 칸에서 출발했을 때, 이동할 수 있는 최대 날짜 수를 구한다.
상하좌우로 이동하면서 현재 칸보다 더 큰 값이 있는 칸으로만 이동이 가능
dp로 방문 지점의 결과를 계산한다.
- 시간복잡도 : O(N^2)
- 공간복잡도 : O(N^2)
dp[x][y][dir][turn]
x,y -> 현재 좌표
dir -> 직전에 이동한 방향
turn -> 같은 방향으로 연속 이동한 횟수
- 시간복잡도 : O(W * H)
- 공간복잡도 : O(W * H)
방향과 연속 이동 횟수를 관리하는게 좀 까다롭게 느껴져서 문제풀이에 시간이 걸렸습니다.

[김지희 / BOJ 골드 3] 욕심쟁이 판다, [김지희 / BOJ 골드 4] 출근 경로

---

15주차/semin/BOJ_홍익 투어리스트.java

TreeSet을 활용하여 명소 위치를 정렬 저장하고, 순차적 명령에 따라 갱신 및 거리 계산을 수행했다.
ceiling 함수를 통해 현재 또는 그 이후 명소를 빠르게 찾았다.
- 시간 복잡도: (Q log N)
- 공간복잡도 : O(N)

[박세민 / BOJ 골드 3] 홍익 투어리스트

---

16주차/semin/Programmers_배달.java

플로이드-워셜 알고리즘으로 모든 노드 간 최단 거리를 구했다.
1번 마을에서 각 마을까지의 최단 거리 중 K 이하인 마을 수를 세었다.
중복된 도로는 더 짧은 거리만 반영하여 초기화했다.
- 시간복잡도: O(N^3)
- 공간복잡도: O(N^2)

[박세민 / 프로그래머스 Lv.2] 배달

---

15주차/huiyeong/Programmers_n^2 배열 자르기.java
16주차/huiyeong/Programmers_모음사전.java

처음에 문제를 봤을 때 모든 n x n 만큼의 배열을 만들면 메모리 부족이 일어날 것이라고 생각했습니다. 그래서 정답인 위치만 하려고 노력했습니다.
- 시간복잡도 : O(right - left + 1)
- 공간복잡도 : O(right - left + 1)
간단하게 풀 수 있는 문제였습니다.
가중치 부분을 Math.pow()로 해결하고 싶었는데 정확히 방법을 모르겠어서 결국 직접 가중치를 넣는 방식으로 진행했습니다.
- 시간복잡도 : O(L)
- 공간복잡도 : O(L)
간단하게 풀 수 있는 문제였습니다.

[김희영/ 프로그래머스 Lv.2] n^2 배열 자르기 / [김희영/ 프로그래머스 Lv.2] 모음사전

---

16주차/semin/Programmers_외벽 점검.java

dist의 모든 순열을 만들어 각 친구 순서대로 투입하며 점검 가능한 최소 인원을 찾는다.
원형 구조를 처리하기 위해 weak 배열을 2배 확장했다.
각 시작점을 기준으로 완전탐색하며 최솟값을 갱신했다.
시간복잡도: O(W × D!)
공간복잡도: O(W×2 + D)

[박세민 / 프로그래머스 Lv.3] 외벽 점검

---

15주차/huiyeong/Programmers_N개의 최소공배수.java
16주차/huiyeong/Programmers_연속 부분 수열 합의 개수.java

최대공약수를 나누어주는 방식으로 하면 되기 때문에 간단하게 구할 수 있었습니다.
- 시간복잡도 : O(N * log M)
- 공간복잡도 : O(1)
처음에는 배열을 새로 만들 생각하지 않고 진행하려고 했는데 원형이기 때문에 윈도우 슬라이드 개념을 쓰면 좋을 것 같다는 생각을 해서 크기가 2배인 배열을 만들어서 진행했습니다.
- 시간복잡도 : O(N^2)
- 공간복잡도 : O(N^2)

[김희영 / 프로그래머스 Lv.2] N개의 최소공배수 / [김희영 / 프로그래머스 Lv.2] 연속 부분 수열 합의 개수

---

16주차/jihee/BOJ_퇴사2.java

dp에 현재 날짜에 기록된 금액 ,지금까지 누적금액 + 현재 날짜 금액 중 더 큰 금액 저장하여 최대값을 출력
- 시간복잡도 :  O(N)
- 공간복잡도 : O(N)
dp로 어렵지 않게 풀 수 있었다.

[김지희/ BOJ 골드 5] 퇴사 2

---

16주차/semin/Programmers_양궁 대회.java

백트래킹을 통해 화살의 중복 조합을 구성하고 각 경우에 점수를 계산한다.
라이언이 어피치를 이기는 경우만 고려하며 최대 점수 차이를 저장한다.
동점일 경우 낮은 점수를 더 많이 맞힌 경우를 우선한다.
- 시간복잡도: O(11^n)
- 공간복잡도: O(1)

[박세민 / 프로그래머스 Lv.2] 양궁 대회

---

15주차/huiyeong/Programmers_행렬의 곱셈.java
16주차/huiyeong/Programmers_더 맵게.java

for 문을 3번 돌려야 하기 때문에 시간복잡도가 걱정되었지만 크기가 작아서 잘 실행되었습니다. 
- 시간복잡도 : O(N × M × K)
- 공간복잡도 : O(N × K)
시간복잡도에 대해서 항상 생각해야 겠다고 느꼈습니다.
우선순위 큐를 생각하면 금방 해결할 수 있는 문제였습니다.
- 시간복잡도 : O(log N)
- 공간복잡도 : O(N)

[김희영 / 프로그래머스 Lv.2] 행렬의 곱셈 / [김희영 / 프로그래머스 Lv.2] 더 맵게

---

16주차/jihee/BOJ_보물섬.java

모든 육지('L') 지점을 시작점으로 하여 BFS를 돌린다.
BFS를 통해 해당 지점에서 도달 가능한 육지들 중 가장 멀리 있는 지점까지의 거리를 계산
- 시간복잡도 : O(N * M)
- 공간복잡도 : O(N * M)
BFS로 어렵지 않게 풀 수 있었다.

[김지희/ BOJ 골드 5] 보물섬

---

16주차/jaemo/BOJ_랜선 자르기.java
16주차/jaemo/BOJ_좋다.java

배열을 오름차순 정렬한 뒤, 투 포인터로 어떤 두 수의 합이 되는 숫자의 개수를 카운팅했습니다.
- 시간복잡도 : `O(n^2)`
- 공간복잡도 : `O(n)`
처음에 음수를 고려하지 못해 계속 틀렸습니다. 문제를 잘 읽어야겠어요..
---
투 포인터로 구한 중간값으로 랜선 개수를 구하고, 보다 작으면 최솟값을 중간값+1로, 보다 크면 최댓값을 중간값-1로 설정합니다.
이를 반복하다가 min이 max보다 커지는 시점에 중간값을 출력합니다.
- 시간복잡도 : `O(klog(max))`
- 공간복잡도 : `O(k)`

[한재모 / 백준 골드 4] 좋다 | [한재모 / 백준 실버 2] 랜선 자르기

---

15주차/huiyeong/Programmers_다리를 지나는 트럭.java
16주차/huiyeong/Programmers_두 큐 합 같게 만들기.java

선입선출이기 때문에 큐를 사용했습니다.
- 시간복잡도 : O(N + bridge_length)
- 공간복잡도 : O(bridge_length)
문제에 큐를 사용하기 때문에 큐를 사용했습니다.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)

[김희영/ 프로그래머스 Lv.2] 다리를 지나는 트럭 / [김희영/ 프로그래머스 Lv.2] 두 큐 합 같게 만들기

---

17주차/semin/BOJ_민서의 응급 수술.java

DFS를 통해 "연결 요소"의 개수를 구한 뒤,
그래프를 연결하고 트리 형태로 만들기 위해 필요한 간선 수를 계산했다.
추가할 간선과 제거할 간선 수를 조합하여 최종 결과를 도출했다.
- 시간복잡도: O(N + M)
- 공간복잡도: O(N + M)

[박세민 / BOJ 골드 4] 민서의 응급 수술

---

16주차/jihee/BOJ_촌수계산.java
17주차/jihee/BOJ_4485.java

p1, p2 사이의 촌수(간선 거리)를 구하는 문제
DFS로 p1에서 시작해 p2까지 도달하는 경로의 깊이를 저장한다.
- 시간복잡도 : O(N^2)
- 공간복잡도 : O(N^2)
다익스트라를 사용해서 , 비용이 적은 칸을 우선적으로 탐색
PriorityQueue를 사용하여 최소 비용 순으로 탐색한다.
- 시간복잡도 : O(N^2)
- 공간복잡도 : O(N^2)

[김지희/ BOJ 실버 2] 촌수계산, [김지희/ BOJ 골드 4] 녹색 옷 입은 애가 젤다지?

---

17주차/jihee/BOJ_트리색칠하기.java

BFS로 현재 노드의 색이 color[i]와 다르면 칠하고 자식 노드에는 부모 노드의 색을 물려준다.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)

[김지희 / BOJ 골드 5] 트리 색칠하기

---

17주차/semin/BOJ_용액 합성하기.java

두 포인터를 양 끝에서 시작하여 배열을 탐색하며 가장 0에 가까운 합을 찾는다.
값의 절댓값이 최소가 되는 순간을 갱신한다.
음수면 왼쪽 포인터를, 양수면 오른쪽 포인터를 조정한다.
- 시간복잡도: O(N)
- 공간복잡도: O(1)

[박세민 / BOJ 골드 5] 용액 합성하기

---

17주차/jaemo/BOJ_캐슬 디펜스.java

적을 공격하는 로직과 적이 이동하는 로직을 각각 따로 구현하여, 백트래킹으로 각 궁수의 위치마다 최댓값을 구하도록 했습니다.
공격 로직의 경우, BFS를 활용해 최단거리 적들을 list에 넣고, 가장 가까운 왼쪽에 있는 적을 공격하도록 했습니다.
- 시간복잡도 : `O(N^2*M^4)`
- 공간복잡도 : `O(N*M)`
복잡한 구현 문제다보니, 중간에 디버깅이 좀 까다로웠습니다.

[한재모 / 백준 골드 3] 캐슬 디펜스

---

17주차/huiyeong/잃어버린 강아지.java

어제 문제와 마찬가지로 방향을 가지고 움직이는 문제였습니다.
- 시간복잡도 : O(T) 
- 공간복잡도 : O(1)

[김희영] 잃어버린 강아지

---

17주차/jihee/BOJ_등산마니아.java

모든 정점 쌍은 무조건 하나의 경로를 가지며, 그 경로는 트리의 유일한 최단 경로이다.
→ 간선을 기준으로 이 경로 쌍을 나누는 것이 핵심이다.
간선 하나를 제거하면 트리는 두 개의 그룹으로 나뉘고, 해당 간선을 지나는 쌍은 서브트리 크기 × 나머지 크기 이다.
DFS를 통해 각 서브트리의 크기를 구한다.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
아이디어만 잘 떠올리면 생각보다는 어렵지 않게 풀 수 있는 문제였다.

[김지희/ BOJ 플레 5] 등산마니아

---

17주차/semin/BOJ_작업.java

위상 정렬 개념을 기반으로, 선행 작업이 없는 경우 해당 작업을 즉시 시작하도록 타임테이블에 기록한다.
매 시간마다 완료된 작업을 기준으로 다음 작업의 진입 차수를 줄이며 작업 순서를 결정한다.
각 작업이 끝나는 시간을 타임테이블에 기록하며, 전체 프로젝트의 최소 완료 시간을 갱신해나간다.
- 시간복잡도: O(N + E)
- 공간복잡도: O(N + T)

[박세민 / BOJ 골드 4] 작업

---

17주차/jaemo/BOJ_스타트링크.java
17주차/jaemo/BOJ_용돈 관리.java

BFS를 활용해 최단 거리를 구하는 방식으로 풀었습니다.
- 시간복잡도 : `O(F)`
- 공간복잡도 : `O(F)`
예외 처리가 중요한 문제로, 만약 실제 시험에서 꼼꼼하게 체크하지 않으면 감점이 많았을 것 같습니다.
---
매번 가능한 인출 금액을 이분 탐색하며, 각 금액에 대해 인출 횟수를 계산해 조건을 만족하는 값을 찾도록 했습니다.
- 시간복잡도 : `O(nlog10^9)`
- 공간복잡도 : `O(n)`

[한재모 / 백준 실버 1] 스타트링크 | [한재모 / 백준 실버 1] 용돈 관리

---

17주차/jihee/BOJ_소형기관차.java

[김지희/ BOJ 골드 3] 소형기관차

---

18주차/semin/BOJ_수 고르기

입력값을 오름차순 정렬한 뒤, 투 포인터 방식으로 두 값의 차이가 m 이상인 경우 중 최솟값을 구한다.
a[en] - a[st]가 m 이상이 되는 첫 지점을 찾으면 그 차이로 최솟값을 갱신한다.
정렬 후 선형 탐색이므로 효율적으로 조건을 만족하는 쌍을 찾을 수 있다.
- 시간복잡도: O(N log N)
- 공간복잡도: O(N)

[박세민 / BOJ 골드 5] 수 고르기

---

18주차/jaemo/BOJ_주사위 굴리기.java

주사위를 1차원 배열로 나타내고, 각 인덱스를 면 위치로 잡습니다. 그리고나서 주사위를 굴리는 방향에 따라 메서드를 각각 구현했습니다.
- 시간복잡도 : `O(nm)`
- 공간복잡도 : `O(nm)`
당연히 x가 row, y가 col인 줄 알고 순서 바꿨다가 시간 날렸습니다.. 앞으로는 입력 조건 잘 보기..

[한재모 / 백준 골드 4] 주사위 굴리기

---

18주차/jihee/BOJ_환상의 짝꿍.java

에라토스테네스의 체를 통해 2000000 이하의 소수를 미리 구한다. 
(A + B)가 짝수면 YES
홀수일 경우, (A + B - 2)가 소수이면 YES
- 시간복잡도 : O(√(A+B))
- 공간복잡도 : O(N)
수 범위가 커 보이지만, 핵심 조건을 체크해서 풀이하면 시간초과가 나지 않는다.

[ 김지희 / BOJ 골드 3] 환상의 짝꿍

---

18주차/semin/BOJ_대표 선수.java

각 학생의 능력치와 소속 팀 정보를 리스트에 저장한 후 오름차순 정렬한다.
투 포인터를 이용해 한 구간에 모든 팀이 포함될 때까지 오른쪽 포인터를 확장하고, 구간 내 최소 능력치 차이를 갱신한다.
모든 시작 인덱스를 기준으로 완전탐색을 하여 최솟값을 찾는다.
- 시간복잡도: O(N × M)
- 공간복잡도: O(N × M)

[박세민 / BOJ 골드 2] 대표 선수

---

18주차/jihee/BOJ_영재의시험.java

백트래킹을 이용하여 풀이
10문제를 모두 채웠을 때 cnt >= 5인 경우에만 결과 카운트
- 시간복잡도 : O(5^10)
- 공간복잡도 : O(N)

[김지희 / 백준 실버 2] 영재의 시험

---

18주차/huiyeong/Programmers_게임 맵 최단거리.java

모든 거리를 다 탐색할 필요가 없기 때문에 BFS를 선택했습니다.
- 시간복잡도 : O(N × M)
- 공간복잡도 : O(N × M)

[김희영 / 프로그래머스 Lv.2] 게임 맵 최단거리

---

18주차/jaemo/CT_편안한 워크숍.java

3차원 dp 배열을 정의하고, 각 depth마다 최적의 값을 도출하는 방식으로 풀었습니다.
- 시간복잡도 : `O(N^2*K)`
- 공간복잡도 : `O(N^2*K)`
시간 복잡도를 고려해 메모이제이션 최적화하는 로직 구현이 너무 어려웠어요. . .

[한재모 / 코드트리 L13] 편안한 워크숍

---

18주차/jihee/BOJ_캠프준비.java

문제 난이도 배열을 정렬 후, 조합을 통해 2 ~ N개 문제를 고름
각 조합에 대해 난이도 총합이 [L, R] 사이인지
최대 - 최소가 X 이상인지 확인
- 시간복잡도 : O(2^N)
- 공간복잡도 : O (N)

[김지희 / 백준 골드 5] 캠프준비

---

18주차/semin/BOJ_음악프로그램.java

입력받은 가수의 순서를 방향 그래프로 구성하고 위상 정렬을 통해 전체 순서를 결정한다.
진입 차수가 0인 정점을 시작점으로 하여 BFS로 정렬을 수행한다.
정렬된 결과의 크기가 전체 가수 수와 다르면 순서 구성이 불가능한 것으로 간주한다.
- 시간복잡도: O(N + M) 
- 공간복잡도: O(N + M)

[박세민 / BOJ 골드 3] 음악프로그램

---

18주차/huiyeong/Programmers_점 찍기.java

문제 자체는 간단하게 구현문제였습니다.
처음에는 int * int 로 제곱을 계산했지만, d가 최대 1,000,000까지 가능해 int 범위를 초과하는 문제가 발생했습니다.  
이를 해결하기 위해 long으로 캐스팅하여 범위 초과를 방지했습니다.
- 시간복잡도 : O(d / k)
- 공간복잡도 : O(1)

[김희영 / 프로그래머스 Lv.2] 점 찍기

---

18주차/huiyeong/Programmers_가장 큰 정사각형 찾기.java

DP로 간단하게 풀 수 있었습니다.
- 시간복잡도 : O(N·M)
- 공간복잡도 : O(1)

[김희영 / 프로그래머스 Lv.2] 가장 큰 정사각형 찾기

---

19주차/semin/BOJ_N과 M (9).java

입력된 수열을 정렬하여 사전순 순서를 보장하며 백트래킹으로 길이가 M인 순열을 생성했다.
중복 수 방지를 위해 이전 값과 같은 경우에는 방문 여부를 체크해 건너뛰었다.
방문 배열을 사용해 한 수를 중복해서 선택하지 않도록 했다.
- 시간복잡도: O(N! / (N-M)!)
- 공간복잡도: O(N + M)

[박세민 / BOJ 실버 2] N과 M (9)

---

19주차/huiyeong/Programmers_[1차] 뉴스 클러스터링.java

- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
문자인지 체크해야 하는 부분이 조금 어려웠지만 Character메서드를 사용해서 해결할 수 있었습니다.

[김희영 / 프로그래머스 Lv.2] [1차] 뉴스 클러스터링

---

19주차/huiyeong/Programmers_피로도.java

모든 경우를 알아야 하고 끝나면 다시 방문 여부를 false로 바꿔줘야 하기 때문에 백트래킹을 사용했습니다.
- 시간복잡도 :  O(n!)
- 공간복잡도 :  O(n)

[김희영 / 프로그래머스 Lv.2] 피로도

---

19주차/semin/BOJ_Gaaaaaaaaaarden.java

후보 위치들 중 G, R 배치를 모든 순열로 시도하여 BFS로 퍼뜨린다.
같은 시간에 다른 색이 도착하면 꽃으로 변환하고 개수를 센다.
배열 순열 생성을 위해 nextPermutation을 구현하여 모든 경우를 탐색했다.
- 시간복잡도: O(P × N×M) (P: 후보 배치 순열 수)
- 공간복잡도: O(N × M)
하아..

[박세민 / BOJ 골드 1] Gaaaaaaaaaarden

---

19주차/huiyeong/Programmers_네트워크.java

전형적인 DFS/BFS 문제였습니다.
- 시간복잡도 : O(n^2)
- 공간복잡도 : O(n)

[김희영/ 프로그래머스 Lv.3] 네트워크

---

19주차/huiyeong/좌석번호.java

저번에 했던 문제에서 간단히 변형된 문제엿습니다.
- 시간복잡도 : 
- 공간복잡도 : 
90도 회전해서 해결하는 부분이 다양한 시각을 가질 수 있도록 해줬습니다.

[김희영] 좌석번호

---

19주차/semin/BOJ_암호 만들기.java

입력된 문자를 오름차순 정렬 후, 백트래킹으로 가능한 모든 조합을 탐색했다.
선택한 문자 수가 L이 되면 모음 1개 이상, 자음 2개 이상 조건을 확인해 출력했다.
output 배열에 현재 문자를 저장하며 이전 인덱스 이후만 탐색해 순서를 유지했다.
시간복잡도: O(L × L)
공간복잡도: O(C + L)

[박세민 / BOJ 골드 5] 암호 만들기

---

19주차/jihee/BOJ_숫자판 점프.java

상하좌우로 인접한 칸을 이동하면서 6자리 숫자를 만든다.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
DFS로 어렵지 않게 풀 수 있었다.

[김지희 / BOJ] 숫자판 점프

---

20주차/jaemo/BOJ_상어 초등학교.java

문제 풀이에 앞서, 순서도를 그려 최대한 로직 누락 없이 설계했고, 각 액션을 메서드 단위로 잘게 쪼갰습니다.
그리고나서 순서도에 따라 분기처리로 로직을 구현했습니다.
- 시간복잡도 : `O(N^4)`
- 공간복잡도 : `O(N^2)`
순서도를 그리지 않았다면 절대 못 풀었을 것 같아요.. 디버깅하다가 포기했을듯..

[한재모 / 백준 골드 5] 상어 초등학교

---

20주차/jihee/BOJ_트리색칠하기.java
20주차/jihee/BOJ_트리의지름.java

[김지희 / BOJ 골드] 트리의 지름, 트리 색칠하기 

---

20주차/semin/BOJ_가장 긴 증가하는 부분 수열 4.java

주어진 수열에서 가장 긴 증가 부분 수열(LIS)을 DP로 구했다.
각 위치에서 이전 원소와 비교하며 길이를 갱신하고, 추적 배열로 경로를 저장했다.
최대 길이를 찾은 뒤 역추적하여 실제 수열을 출력했다.
- 시간복잡도: O(N^2)
- 공간복잡도: O(N)

[박세민 / BOJ 골드 4] 가장 긴 증가하는 부분 수열 4

---

20주차/jihee/BOJ_트리와쿼리.java
20주차/jihee/BOJ_트리의높이와너비.java

루트를 기준으로 DFS 한 번 돌며 각 노드의 서브트리 크기를 미리 구함
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
dfs로 미리 처리해두면 효율적으로 계산할 수 있다.
루트를 찾아서 각 노드의 열 번호를 기록한다.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)

[김지희 / BOJ 골드 5 ] 트리와 쿼리, [김지희 / BOJ 골드 2 ] 트리의 높이와 너비

---

20주차/jaemo/BOJ_센서.java
20주차/jaemo/PG_기능개발.java

큰 인접 간격부터 (K-1)개를 경계로 잘라 K개의 구간을 만듭니다. 그리고나서 남은 간격들의 합을 더하면, 그 값이 최소한의  총 수신 길이입니다.
- 시간복잡도 : `O(nlogn)`
- 공간복잡도 : `O(n)`
어려워서 답지 봤어요.. 그래도 어렵네요
---
Queue에 개발 기간(`(100-progress)/speed` or `(100-progress)/speed+1`)을 모두 담고, 차례로 꺼내면서 큐에 남아 있는 기간이 더 짧거나 같으면 함께 꺼내 카운팅하도록 했습니다.
- 시간복잡도 : `O(n)`
- 공간복잡도 : `O(n)`
큐 기초 문제였습니다.

[한재모 / 백준 골드 5] 센서 | [한재모 / 프로그래머스 Lv.2] 기능개발
